### ISSUE TITLE
Is there a way to disable data sampling?

### ISSUE THREAD

**Issue by haozhouamzn** [EleutherAI/gpt-neox#1005]
**Is your feature request related to a problem? Please describe.**
Looks like with multiple datasets, e.g. in [local_setup.yml](https://github.com/EleutherAI/gpt-neox/blob/main/configs/local_setup.yml#L9), each dataset will be sampled certain % of data. For example, with two datasets, and each has 100 samples with weights [1,2]. Then it ends up with 33 samples from dataset A, and 66 samples from dataset B. 

Is there a way to keep 100 samples of dataset A and 100 samples of dataset B? 

**Describe the solution you'd like**
A flag or instruction on which codes need to be changed. 

**Describe alternatives you've considered**
Overwrite the `ratio` in [helper.cpp](https://github.com/EleutherAI/gpt-neox/blob/8b3f1c28555ccad92e3b0906c71528be712c95d6/megatron/data/helpers.cpp#L83-L84). 

**Additional context**
I have a very large dataset, and I have to partition it into multiple small ones in order to process to mmap files. I want to train the model with all data.

**Comment by StellaAthena** [comment]
Is there a reason why using weights of [1, 1] doesn't accomplish what you want?
