### ISSUE TITLE
Issues installing - Bare with me please

### ISSUE THREAD

**Issue by MistakingManx** [EleutherAI/gpt-neox#1006]
**Describe the bug**
I'm trying to install it to test it out, but I'm not quite sure how to proceed, it's throwing an error when I run the last install command.
Furthermore, the first install command had an error, but I decided to ignore it in hopes that it didn't matter much.

**To Reproduce**
1. Run the install commands

**Expected behavior**
Easy install of requirements and anything else it needs

**Proposed solution**
Help the noob out, that being me

**Errors**
`ERROR: Could not build wheels for mpi4py which use PEP 517 and cannot be installed directly`
```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.16) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "./megatron/fused_kernels/setup.py", line 23, in <module>
    _, bare_metal_major, _ = _get_cuda_bare_metal_version(cpp_extension.CUDA_HOME)
  File "./megatron/fused_kernels/setup.py", line 10, in _get_cuda_bare_metal_version
    [cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Environment (please complete the following information):**
 - GPUs: None (it could just use my CPU instead right?)
- Configs: None, yet.

**Additional context**
I usually work with Node.JS, please forgive my lack of know-how with Python.

**Comment by StellaAthena** [comment]
This often happens when your pip is out of date or you have a system conflict with the instillation.

However if you don’t have GPUs there’s no reason to install this library. I’m not sure if the library runs on CPU, but it definitely isn’t the right tool for the job. You should check out libraries designed for CPU usage, like ggml or the HuggingFace transformers library.
