### ISSUE TITLE
can you provide pre-built images for main branch

### ISSUE THREAD

**Issue by xu-song** [EleutherAI/gpt-neox#1019]
Both gpt-neox 1.0 and 2.0 are based on torch 1.8. Can you provide pre-built images for main branch, which based on torch 1.13

**Comment by Quentin-Anthony** [comment]
We've updated our Dockerfile to be based on the NGC PyTorch container, which provides torch 2.3.0

Does this resolve your issue, or do you need 1.13 specifically?
