### ISSUE TITLE
some Datasets are not available

### ISSUE THREAD

**Issue by vangogh0318** [EleutherAI/gpt-neox#1071]
**Describe the bug**
can not download the github/ArXiv dataset. the url is wrong
how to download github/ArXiv data? thank you

The code in corpora.py file, line 190:
class Github(DataDownloader):
    name = "github"
    urls = ["http://eaidata.bmk.sh/data/github_small.jsonl.zst"]

class ArXiv(DataDownloader):
    name = "arxiv"
    urls = [
        "https://the-eye.eu/public/AI/pile_preliminary_components/2020-09-08-arxiv-extracts-nofallback-until-2007-068.tar.gz"
    ]

**Comment by StellaAthena** [comment]
This is correct. The Pile has been taken down to a DMCA takedown request.

**Comment by vangogh0318** [comment]
hi, how can I access the Pile data? Thanks
@vangogh0318
