### ISSUE TITLE
Apply new fused rotary embedding

### ISSUE THREAD

**Issue by Quentin-Anthony** [EleutherAI/gpt-neox#1077]
This could really help us: https://github.com/NVIDIA/apex/pull/1746

**Comment by Quentin-Anthony** [comment]
May also need https://github.com/NVIDIA/apex/pull/1750 applied in order to test FYI

**Comment by StellaAthena** [comment]
This is naively ported but untested.

**Comment by Quentin-Anthony** [comment]
> This is naively ported but untested.

Huh? Please clarify.

**Comment by StellaAthena** [comment]
> > This is naively ported but untested.
> 
> Huh? Please clarify.

Sorry, that was a progress update. I've ported the code changes to GPT-NeoX but haven't had a chance to test them yet.

**Comment by Quentin-Anthony** [comment]
> > > This is naively ported but untested.
> > 
> > 
> > Huh? Please clarify.
> 
> Sorry, that was a progress update. I've ported the code changes to GPT-NeoX but haven't had a chance to test them yet.

Gotcha.

**Comment by Quentin-Anthony** [comment]
@StellaAthena -- Can you write up what you have into a draft PR? We can offload testing from you.

**Comment by StellaAthena** [comment]
@Quentin-Anthony They're not ready for testing yet, but I can still open a draft PR if you'd like. Right now I'm in a place where I think I've copied over all of the core code but the kernels aren't building and I haven't been able to debug why that is yet.

I had hoped to make more progress on this last week, but got swamped with some other stuff. I'm happy to hand it off if someone else wants to take it over.

**Comment by Quentin-Anthony** [comment]
> @Quentin-Anthony They're not ready for testing yet, but I can still open a draft PR if you'd like. Right now I'm in a place where I think I've copied over all of the core code but the kernels aren't building and I haven't been able to debug why that is yet.
> 
> I had hoped to make more progress on this last week, but got swamped with some other stuff. I'm happy to hand it off if someone else wants to take it over.

Yes please make a draft PR

**Comment by yang** [comment]
@StellaAthena Still wanting help getting this to work / testing this?

**Comment by StellaAthena** [comment]
> @StellaAthena Still wanting help getting this to work / testing this?

That would be excellent, thank you.
