### ISSUE TITLE
Finetune

### ISSUE THREAD

**Issue by liuxinxin123** [EleutherAI/gpt-neox#1088]
Can we support instruction finetune?

**Comment by StellaAthena** [comment]
Nothing special is required to do instruction-finetuning. It's the same as normal finetuning, just with different data.

if you're interested in RLHF, that's not something we plan on supporting, however there are libraries such as [trl](https://github.com/huggingface/trl) and [trlX](https://github.com/CarperAI/trlx) that support this. The later library has a WIP integration with GPT-NeoX

**Comment by iNeil77** [comment]
Hi @StellaAthena, I think you mean (If I'm not mistaken) to line up the instruct data as an append of instruction and response and continue with regular LM training. However, for most instruction tuning, it is standard to mask the gradient updates for the instruction and only backdrop them for the response. Does the framework make this possible?

**Comment by StellaAthena** [comment]
There's an open PR for this [here](https://github.com/EleutherAI/gpt-neox/pull/1240). We also have started implementing RLHF features since my comment, e.g., [this](https://github.com/EleutherAI/gpt-neox/pull/1242) and [this](https://github.com/EleutherAI/gpt-neox/pull/1244).

**Comment by StellaAthena** [comment]
> Hi @StellaAthena, I think you mean (If I'm not mistaken) to line up the instruct data as an append of instruction and response and continue with regular LM training. However, for most instruction tuning, it is standard to mask the gradient updates for the instruction and only backdrop them for the response. Does the framework make this possible?

There's an open PR adding support for this [here](https://github.com/EleutherAI/gpt-neox/pull/1240). We also have started implementing RLHF features since my comment, e.g., [here](https://github.com/EleutherAI/gpt-neox/pull/1242) and [here](https://github.com/EleutherAI/gpt-neox/pull/1244).

**Comment by iNeil77** [comment]
Thanks for the reply! Will check it out
