### ISSUE TITLE
Support for lm_eval 0.4.0

### ISSUE THREAD

**Issue by ZhiYuanZeng** [EleutherAI/gpt-neox#1114]
I hope gpt-neox to support lm-eval==0.4.0. The current gpt-neox evaluate the models on benchmarks with lm-eval==0.3.0, which does not support many important datasets, for example, mmlu.

**Comment by StellaAthena** [comment]
@haileyschoelkopf i thought you had fixed this?

**Comment by haileyschoelkopf** [comment]
I thought so too. Though I’ll make a PR to bump the dependency now that we put 0.4.0 on pypi

**Comment by ZhiYuanZeng** [comment]
Perhaps it's because I'm still using the old version of gpt-noex. I'll check the differences with the latest version. Thanks for your help! By the way, could you tell me the commit ID where this issue was fixed?

**Comment by StellaAthena** [comment]
@ZhiYuanZeng It's [here](https://github.com/EleutherAI/gpt-neox/commit/b27e409cf6c3b78a073681d8a312b1c1477fd703)
