### ISSUE TITLE
NameError: name 'RepeatingLoader' is not defined

### ISSUE THREAD

**Issue by Carolingliang** [EleutherAI/gpt-neox#112]
![image](https://user-images.githubusercontent.com/78017166/106706333-80c53700-662a-11eb-9313-d433948aee5d.png)

**Comment by StellaAthena** [comment]
Hi! Can you give us some more details about your hardware set-up, what code you ran, what settings you used, etc.?

**Comment by Carolingliang** [comment]
hardware set-up:   cpu is eighty cores, memory is 1t, gpu is 3090 with eight 24G
code:   deepspeed train_pipeline.py --deepspeed_config=configs/gpt3_small.json

**Comment by StellaAthena** [comment]
Try `deepspeed train_pipeline.py --deepspeed -–deepspeed_config=configs/deepspeed_zero1.json`

**Comment by Carolingliang** [comment]
It still has this bug.  
Maybe the path of "RepeatingLoader" was not found.
But I didn't find the function"RepeatingLoader" in this project.

**Comment by StellaAthena** [comment]
`deepspeed.utils.RepeatingLoader` is a wrapper around an itterable that you can use to define data-loaders in DeepSpeed. You can see where we use it [here](https://github.com/EleutherAI/gpt-neox/blob/3291d0e6c867d9d328b96e8377f5b77c6f66c323/train_pipeline.py#L55). I don't see how it could error for you and not for others, but try replacing that line with `deepspeed.utils.RepeatingLoader` to explicitly import it.

**Comment by Carolingliang** [comment]
ok ,thanks
