### ISSUE TITLE
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

### ISSUE THREAD

**Issue by Carolingliang** [EleutherAI/gpt-neox#114]
running "deepspeed train_pipeline.py --deepspeed --deepspeed_config=configs/checkpoints_config.json"

Then I get a bug as the picture shows：
![image](https://user-images.githubusercontent.com/78017166/106852921-d31e5a80-66f3-11eb-83a4-26b36fba7844.png)

**Comment by StellaAthena** [comment]
You need to either set up and log into an WandB account or disable WandB on
tjrs
