### ISSUE TITLE
Error on inference of huggingface

### ISSUE THREAD

**Issue by mackmake** [EleutherAI/gpt-neox#1142]
hi again
i converted my trained model to HF with the code in /tools/dataset. I wanted to fine-tune the HF model using `SFTTrainer` but i got this error:
```
gptneoxmodel.forward() got an unexpected keyword argument 'labels'
```
I used either a dataset from HF or my own `.jsonl` dataset with 'text' column each row.
why this problem happens and how can i solve the problem?

**Comment by StellaAthena** [comment]
This sounds more likely to be a problem with the training set-up than our conversion code. Can you run inference in the `transformers` library?

**Comment by mackmake** [comment]
sorry for mistake. i had loaded model with AutoModel.
loading it with AutoModelForCausalLM did the work ^_^
thank you very much
