### ISSUE TITLE
files in multi-node training

### ISSUE THREAD

**Issue by mackmake** [EleutherAI/gpt-neox#1146]
i want to trin on multi-node. is it necessary to copy preprocessed dataset file and tokenizer to all nodes? or all nodes read these files from master node?

**Comment by StellaAthena** [comment]
Typically we store them in a shared file storage system that every node has access to, but if you are training multi-node and require locally storage data then yes you'll need to share them across the storage systems.

**Comment by mackmake** [comment]
thnks shared memory was a nice idea ^_^
