### ISSUE TITLE
How to convert gpt-neox to llama architecture..?

### ISSUE THREAD

**Issue by yuri-son** [EleutherAI/gpt-neox#1151]
Hello developer,

I want to replacing the polyglot based on gpt-neox model with the llama tokenizer and model architecture.
 Could you please advise if there's a way to make this conversion?

**Comment by StellaAthena** [comment]
GPT-NeoX is a library for training models, not a specific architecture. You can find the configs for training a model using the LLaMA architecture [in our example configs](https://github.com/EleutherAI/gpt-neox/tree/main/configs/llama).
