### ISSUE TITLE
continue training from a checkpoint with different number of gpu/node

### ISSUE THREAD

**Issue by mackmake** [EleutherAI/gpt-neox#1158]
hi
i get a checkpoint  of a model trained on multi node from my friend. can i run it in another node with different number of gpus? how about multi-node with different number of gpus from my friend?

**Comment by Quentin-Anthony** [comment]
This is a non-trivial feature and hasn't yet been added.

It's still in-progress at https://github.com/EleutherAI/gpt-neox/pull/836
