### ISSUE TITLE
Dockerfile installation fails to run pythia 14M

### ISSUE THREAD

**Issue by tf-nv** [EleutherAI/gpt-neox#1165]
I wanted to give GPT-NeoX a try, and plan to run a quick training on pythia 14M. I saw some issues with the dockerfile and am proposing some fixes, and would be ready to create a PR :)

**Describe the bug**
There are two issues with the current Dockerfile, purely empirically:
1. Apex seems to be built without cuda extensions
```
[...]
  File "/gpt-neox/train.py", line 34, in <module>
    main()
  File "/gpt-neox/train.py", line 30, in main
    pretrain(neox_args=neox_args)
  File "/gpt-neox/megatron/training.py", line 194, in pretrain
    model, optimizer, lr_scheduler = setup_model_and_optimizer(
  File "/gpt-neox/megatron/training.py", line 654, in setup_model_and_optimizer
    optimizer, param_groups = get_optimizer(model=model, neox_args=neox_args)
  File "/gpt-neox/megatron/training.py", line 580, in get_optimizer
    optimizer = adam_optimizer(
  File "/usr/local/lib/python3.10/dist-packages/apex/optimizers/fused_adam.py", line 117, in __init__
    raise RuntimeError('apex.optimizers.FusedAdam requires cuda extensions')
RuntimeError: apex.optimizers.FusedAdam requires cuda extensions
```

Building apex from scratch instead of using the prebuilt not-nvidia-apex wheel solves the issue. Not sure about the cause, the prebuilt wheel build process looks ok. It is true that compilation takes a while (~45 minutes).

Using the nvidia pytorch container as a base instead of the raw cuda container would also be an option. The Pytorch container has torch, apex, openmpi, transformer engine etc. preinstalled and will save even more time. (see [release notes](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-24-02.html) for details)

2. The required version (2.2.1) of the flash-attn package does not support the `window_size` argument:
```
[...]
  File "/-gpt-neox/megatron/model/transformer.py", line 866, in forward
    return forward_call(*args, **kwargs)
    context_layer = self.flash_attention(query_layer, key_layer, value_layer)
  File "/gpt-neox/megatron/model/transformer.py", line 622, in flash_attention
    output = self.flash_qkv_fn(
TypeError: flash_attn_func() got an unexpected keyword argument 'window_size'
```

This is solved by updating `flash-attn` to the latest `2.5.5`

**To Reproduce**
1. Build docker image from current main
2. See above errors
a) fixing apex alone yields the flash-attn error
b) fixing flash-attn yields a pythia config error with `gas` not being recognized, that is a trivial fix :)

**Expected behavior**
The Dockerfile should yield a working installation

**Proposed solution**
1. Build apex properly
2. Update `flash-attn` to 2.5.5

Even better, entirely switch to the ngc pytorch container as a base :)

I would be happy to author an PR, my gut feeling tells me that the pytorch container is the way to go. What do you think?

**Comment by Quentin-Anthony** [comment]
Thanks for the writeup! 

1. The flash bug with window checking was just fixed in https://github.com/EleutherAI/gpt-neox/pull/1162, so I think that's resolved.
2. I completely agree with you that the PyTorch container would resolve a lot of our headaches recently with packages like apex. I would welcome a PR rebasing our image onto pytorch ngc

**Comment by Quentin-Anthony** [comment]
Resolved in https://github.com/EleutherAI/gpt-neox/pull/1170
