### ISSUE TITLE
Deeperspeed

### ISSUE THREAD

**Issue by Thierryonre** [EleutherAI/gpt-neox#120]
Does deeperspeed provide any performance advantages over deepspeed?
I'm also assuming the way to use deeperspeed is the same as deepspeed.

**Comment by StellaAthena** [comment]
DeepSpeed is not fully public. At time of writing it includes hardcoded references to unreleased functions and does not possess all of the features described in the DeepSpeed papers. Our DeeperSpeed is a drop-in replacement for the DeepSpeed library that is almost entirely the same code, with minor bug fixes and our improvements on the components that are not yet public.
