### ISSUE TITLE
How to set the ffn hidden size parameter in gpt neox

### ISSUE THREAD

**Issue by IronMan-WangJinxi** [EleutherAI/gpt-neox#1230]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Quentin-Anthony** [comment]
Will be resolved in https://github.com/EleutherAI/gpt-neox/pull/1212

**Comment by Quentin-Anthony** [comment]
Now merged!
