### ISSUE TITLE
Runtime per step linearly increases with training step number.

### ISSUE THREAD

**Issue by iPRET** [EleutherAI/gpt-neox#1322]
**Describe the bug**
Training step time is takes linearly more time with each training step.

**To Reproduce**
My config for running training was:
[config.yml.txt](https://github.com/user-attachments/files/17732078/config.yml.txt)
Used slurm for launching. Script run by sbatch was:
[launch.sh.txt](https://github.com/user-attachments/files/17732113/launch.sh.txt)

**Expected behavior**
Runtime per train step linearly increases based on train step.
Plot of optimizer step time in ms, based on iteration [data parsed from training logs]:
![image](https://github.com/user-attachments/assets/ede66a1b-4a45-47cd-bb76-930e8fc5f300)
Plot of forward step time in ms, based on iteration:
![image](https://github.com/user-attachments/assets/77bf42af-86d3-4d2d-bb23-389ad9c15648)
Plot of samples per second, based on iteration:
![image](https://github.com/user-attachments/assets/2ed52504-6ddc-4b3c-b5cf-13baa8a2003d)

**Environment:**
Running code on the LUMI supercomputer.
GPUs: Single node run with 8x AMD MI250X GPUs.
Pip list: [pip-list.txt](https://github.com/user-attachments/files/17732561/pip-list.txt)
Python version: 3.6.15
Also modified deeperspeed to wrap each launched training process in a singularity container with srun.

**Additional info:**
Full training log: 
[slurm3.txt](https://github.com/user-attachments/files/17733156/slurm3.txt)

Any ideas what might be the issue?

**Comment by iPRET** [comment]
Update: it did not replicate with the same config on a different server with NVIDIA L40s. 
So I guess it's to do with something to do with the environment.

**Comment by Quentin-Anthony** [comment]
Gotcha! Let us know if you face this again and have reason to believe it's the neox library.
