### ISSUE TITLE
Insufficient support for tokenizer_type

### ISSUE THREAD

**Issue by fxnie** [EleutherAI/gpt-neox#1328]
The current tokenizer type only supports' GPT2BPETekenizer ' HFTokenizer', 'HFGPT2Tokenizer', 'SPMTokenizer', 'CharLevelTokenizer', 'TiktokenTokenizer'， Do you plan to support GPTNeoXTokenizer and Qwen2Tokenizer? Thank you very much

**Comment by StellaAthena** [comment]
`HFTokenizer` supports any tokenizer loadable via the Hugging Face `tokenizer` library (unless they've made breaking changes). `HFGPT2Tokenizer` exists primarily for historical reasons and should not be understood as implying that every individual implementation in the library needs separate support.
