### ISSUE TITLE
train scripts for reproducing 3d-parallel results with megatron-gpt.

### ISSUE THREAD

**Issue by gongjingcs** [EleutherAI/gpt-neox#135]
Hi，

I noticed that you have developed a gpt example using deepspeed 3D pipeline. could you please provide a full tutorial for how to using this example ?

**Comment by StellaAthena** [comment]
Hi @gongjingcs!  We are currently in the middle of revamping and reorganizing our configuration files and API. Fuller documentation will be available soon. For a preview, check out the `config_monster` branch

**Comment by gongjingcs** [comment]
> Hi @gongjingcs! We are currently in the middle of revamping and reorganizing our configuration files and API. Fuller documentation will be available soon. For a preview, check out the `config_monster` branch

thanks alot !

**Comment by StellaAthena** [comment]
You can fun the code with `./deepy.py pretrain_gpt2.py -d configs ds_pretrain_gpt2.yml local_setup.yml` the `.yml` files can both be found in `gpt-neox/configs/`. I recommend starting with running that, and then modifying the configs as necessary. Note that a couple of the other config files are malformated. I’m planning on fixing that today. For a full description of what each parameter does, see `gpt-neox/configs/readme.md`.
