### ISSUE TITLE
10 billion parameters

### ISSUE THREAD

**Issue by Carolingliang** [EleutherAI/gpt-neox#150]
How to adjust the parameters to make the total parameters are 10 billion

If I use NVIDIA GeForce RTX 3090( 8 cards, 24G per card)，could I achieve this？

**Comment by StellaAthena** [comment]
For parameterization suggestions, see Fig 2.1 of [this paper](https://arxiv.org/abs/2005.14165). They don’t list 10B exactly, but they have a 13B model you can use as a baseline.

Unfortunately I don’t really know anything about your GPUs. Give it a shot and let us know!
