### ISSUE TITLE
Ensure Sampling works correctly 

### ISSUE THREAD

**Issue by sdtblck** [EleutherAI/gpt-neox#152]
There's code inherited from megatron for sampling from the model but we should ensure we can get this working with the deepspeed / pipeline parallel model too.

See https://github.com/EleutherAI/gpt-neox/blob/main/tools/generate_samples_gpt2.py

**Comment by joshlk** [comment]
I could pick this up if no one else is

**Comment by StellaAthena** [comment]
> I could pick this up if no one else is

yeah definitely.
