### ISSUE TITLE
Integrate HuggingFace Tokenizers

### ISSUE THREAD

**Issue by sdtblck** [EleutherAI/gpt-neox#190]
Would be good to replace the weird tokenizer class megatron has with HF tokenizers, or at least accept both types of tokenizer. HF library is super intuitive for training and nice and easy to use. This would allow us to experiment with different tokenization schemes, etc.

The tokenizer code is a little spread out through the repo currently so this might be a bit of a task.

**Comment by QazQazaq** [comment]
This feature would be good for adding.

**Comment by QazQazaq** [comment]
Huggingface would be better for adding as it has many functionalities.
