### ISSUE TITLE
Inference with the 2.5B Model

### ISSUE THREAD

**Issue by afiaka87** [EleutherAI/gpt-neox#197]
Hi all, 

I was told to come to this repository from the original gpt-neo repository if I wanted to try to run inference on the released 2.5B model. What's the current status of this repo compared to the old one? Can you run inference on a single GPU with the pretrained model? 

Thanks and great work to everyone working on this.

**Comment by StellaAthena** [comment]
Thank you for your interest, though I think there was a miscommunication. This repo is independent of GPT-Neo and the checkpoints we released so far do not easily load in it.
