### ISSUE TITLE
Are there any hadrdware requirements to implement this model on GPUs?

### ISSUE THREAD

**Issue by bpm246** [EleutherAI/gpt-neox#201]
Aside from the especifications for the deepspeed's sparse attention kernels, are there any other hardware specifiations for implementing the model? Is there an optimal number of GPUs to use?

**Comment by StellaAthena** [comment]
> Aside from the especifications for the deepspeed's sparse attention kernels, are there any other hardware specifiations for implementing the model

This code is a model training framework. There is no pretrained model and you can define the model you wish to train however you like. The only  universal requirements are that you can install `requirements.txt`.

> Is there an optimal number of GPUs to use?

This isn’t a question that has an answer. The amount of GPUs necessary depends on both how long pyou’re willing to wait as well as how large of a model you want to train.
