### ISSUE TITLE
Wikiextractor

### ISSUE THREAD

**Issue by QazQazaq** [EleutherAI/gpt-neox#204]
[WikiExtractor.zip](https://github.com/EleutherAI/gpt-neox/files/6254468/WikiExtractor.zip)
https://github.com/fastai/course-nlp/blob/master/nlputils.py
https://github.com/piegu/fastai-projects/blob/master/nlputils_fastai2.py
**Is your feature request related to a problem? Please describe.**
Wikipedia database dump has a lot of data from multiple languages but there was no training in gpt2 with all languages in Wikipedia dump.

**Describe the solution you'd like**
Using Wikipedia dump data for all languages in Wikipedia to train gpt-neox. The wikiextractor file to be used in nlputils.py and nlputils_fastai2.py code should be the Wikiextractor.py stored in wikiextractor.zip and not the github code being used.

**Describe alternatives you've considered**
Feature to choose any language in Wikipedia for training and using gpt-neox.

**Additional context**
Wikipedia has a lot of data for many languages which can be used for training.

**Comment by StellaAthena** [comment]
We have no idea what the [quality of this dataset is](https://arxiv.org/abs/2103.12028) and are not currently looking to train translation models anyways. Our models are already trained on English language Wikipedia.

**Comment by QazQazaq** [comment]
https://dumps.wikimedia.org/ is the dump and the above code is for processing the dump.
