### ISSUE TITLE
Language translating

### ISSUE THREAD

**Issue by QazQazaq** [EleutherAI/gpt-neox#205]
https://github.com/danielinux7/Multilingual-Parallel-Corpus

**Is your feature request related to a problem? Please describe.**
Language translating is a problem as usually there is less data available for many languages and many languages do not have translating softwares

**Describe the solution you'd like**
Zero Shot translation using Wikipedia dump.

**Describe alternatives you've considered**
Search and find data for many languages to use for translating.

**Additional context**
Data are available for making translation for many languages on internet.

**Comment by StellaAthena** [comment]
We have no idea what the [quality of this dataset is](https://arxiv.org/abs/2103.12028) and are not looking to train translation models anyways.
