### ISSUE TITLE
Failed to install the requirements

### ISSUE THREAD

**Issue by notooth1** [EleutherAI/gpt-neox#223]
I failed to install the requirements. Can anyone help?

```
    gpt-neox$ pip install -r requirements.txt
    ERROR: Could not find a version that satisfies the requirement cupy-cuda111==9.2.148 (from -r requirements.txt (line 9)) (from versions: 8.1.0, 8.2.0, 8.3.0, 8.4.0, 8.5.0, 8.6.0, 9.0.0a1, 9.0.0a2, 9.0.0b1, 9.0.0b2, 9.0.0b3)
    ERROR: No matching distribution found for cupy-cuda111==9.2.148 (from -r requirements.txt (line 9))
```
Note that I changed cupy-cuda111 to 9.2.148 to match my cuda version.

**Comment by StellaAthena** [comment]
> Note that I changed cupy-cuda111 to 9.2.148 to match my cuda version.

[Read the cupy-cuda92 docs here](https://pypi.org/project/cupy-cuda92/).

**Comment by notooth1** [comment]
I changed it to `cupy-cuda92==9.2.148`, but it still had the same error.
