### ISSUE TITLE
Support ZeRO-Infinity 

### ISSUE THREAD

**Issue by bratao** [EleutherAI/gpt-neox#244]
**Is your feature request related to a problem? Please describe.**

I´m frustrated because I can´t use my Geforce MX 250 to train a 13B GPT-NeoX.

**Describe the solution you'd like**

In DeepSpeed v0.3.15 they introduces ZeRO-Infinity, a ZeRO-3 that also checkpoints to disk.

If I understand correctly, after approving https://github.com/EleutherAI/gpt-neox/pull/199 , a merge of https://github.com/EleutherAI/DeeperSpeed with upstream and exposing the parameters:
```
"offload_optimizer": {
      "device": "cpu/gpu/nvme"
    },
    "offload_param": {
      "device": "cpu/gpu/nvme"
    }
```
Would be enough

**Comment by StellaAthena** [comment]
You won't be able to train a 13B GPT-NeoX on a Geforce MX 250 because even if it fits the runtime will be measured in years. At the current time I do not see a use-case for ZeRO-Infinity, making it a low priority.

**Comment by bratao** [comment]
@StellaAthena I know. I was jk about the mx 250. 

However, I do see the use case for training a larger model where a cpu check-pointing/ gradient accumulation would not be enough. But if I understood correctly with https://github.com/EleutherAI/gpt-neox/pull/199 and a newer version of Deeperspeed it is a matter of setting the right values of "zero_optimization"

**Comment by StellaAthena** [comment]
We are deprioritizing ZeRO 3 based on feedback from NVIDIA. This may be implemented in the future, but not for a while I suspect (unless you want to!)

**Comment by bratao** [comment]
Sounds fair @StellaAthena , hopefully in my upcoming vacation I can work on it. 
But I'm curious, can you share the Nvidia feedback?

**Comment by StellaAthena** [comment]
@bratao Basically that the marginal improvement for Z-3 and Z-infinity over Z-1 + pipeline parallelism was minimal at the 100B scale.
