### ISSUE TITLE
Fix depreciated code

### ISSUE THREAD

**Issue by StellaAthena** [EleutherAI/gpt-neox#32]
When you run GPT-3 Small, you get a depreciated code warning because of how we handle iterators.

**Comment by sdtblck** [comment]
to be more specific, it's `tf.io.tfrecord_iterator` here https://github.com/EleutherAI/gpt-neox/blob/main/gpt_neox/datasets.py#L83

I think we should just be able to use https://www.tensorflow.org/api_docs/python/tf/data/TFRecordDataset
