### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by qwertyuu** [EleutherAI/gpt-neox#376]
I wanted to take time to thank @StellaAthena directly (sorry, I could not find contact info to do this in private) for all that you do. I just discovered geometric deep learning and I am eager to learn more. Just found out it can help humans in the medical field.

GPT-neox is very nice also. Thanks for taking time to do such nice things for the human race.

Have a good day

**Comment by StellaAthena** [comment]
Thank you. You can message me on our discord server if you want to contact me in the future.
