### ISSUE TITLE
Write dataset class that tokenizes on the fly

### ISSUE THREAD

**Issue by sdtblck** [EleutherAI/gpt-neox#40]
Our current dataset class leaves a lot to be desired.
Ideally, we would have a dataset class that takes in text data and processes it on the fly, using multiple workers, similar to the dataloader in MegatronLM https://github.com/microsoft/DeepSpeedExamples/blob/master/Megatron-LM/gpt2_data_loader.py

**Comment by StellaAthena** [comment]
Superseded by codebase refactoring.
