### ISSUE TITLE
text_gen_gpt2.py fails with TypeError

### ISSUE THREAD

**Issue by EinoHR** [EleutherAI/gpt-neox#410]
**Describe the bug**
Trying to run `python text_gen_gpt2.py` gives me this error:
```
WARNING: APEX is not installed, using torch.nn.LayerNorm instead of apex.normalization.FusedLayerNorm!
Traceback (most recent call last):
  File "/home/eino/Coding/new-words/gpt-neox/text_gen_gpt2.py", line 27, in <module>
    model, neox_args = setup_for_inference_or_eval()
  File "/home/eino/Coding/new-words/gpt-neox/megatron/utils.py", line 399, in setup_for_inference_or_eval
    neox_args = NeoXArgs.consume_neox_args(overwrite_values=_overwrite_values)
  File "/home/eino/Coding/new-words/gpt-neox/megatron/neox_arguments/arguments.py", line 280, in consume_neox_args
    megatron_config = json.loads(args_parsed.megatron_config)
  File "/home/eino/miniconda3/envs/gpt-neox/lib/python3.9/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
```

**To Reproduce**
1. Install the things recommended in [the quick start](https://github.com/EleutherAI/gpt-neox#quick-start) into a conda environment
2. Run `python text_gen_gpt2.py`

**Expected behavior**
The script only has two optional arguments, and should probably work without any.

**Environment (please complete the following information):**
 - GPUs: RTX 3090
- Configs: Default
- Conda packages: https://hastebin.com/utasuqawiz.txt
- Pip packages: https://hastebin.com/wujepawito.txt

**Additional context**
APEX is not installed because of this error: https://hastebin.com/cesoraluwe.pyerror

**Comment by EricHallahan** [comment]
I see a few problems with your usage that directly conflict the usage specified in the quick start guide: 
1. You are calling <samp>text_gen_gpt2.py</samp> without using the <samp>deepy.py</samp> launcher script. 
2. You are passing no arguments. Regardless of how you launch GPT-NeoX, you should pass a configuration.
3. We provide a basic usage example in the guide using <samp>./configs/small.yml</samp> and <samp>./configs/local_configs.yml</samp>, but you will almost certainly need to customize your own configurations for your system and hardware configuration. If you have a model checkpoint you are trying to load (and presumably you do considering you are trying to generate text), you should load the model with the configuration files saved alongside the checkpoint.

To quote the usage section of the quick start guide: 
> GPT-NeoX parameters are defined in a YAML configuration file which is passed to the `deepy.py` launcher. We provide baseline examples for the models found in the paper [Language Models are Few Shot Learners](https://arxiv.org/abs/2005.14165). Configs such as file locations that are dependant on your particular system go in `local_configs.yml`. We have filled it out with some placeholder examples, but you will need to update this for your system.
> 
> All functionality follows the pattern `./deepy.py main_function.py -d configs small.yml local_configs.yml`
> We currently offer four main functions:
> 1. `pretrain_gpt2.py` is used for training and finetuning models.
> 2. `eval_tasks/run.py` is used to evaluate a trained model using the evaluation harness.
> 3. `text_gen_gpt2.py` is used to sample text from a trained model.


<details><summary>Your usage should be along the lines of <kbd>python ./deepy.py text_gen_gpt2.py -d configs small.yml local_configs.yml</kbd>.</summary>
<dl><dt><kbd>python ./deepy.py</kbd></dt><dd>calls the launcher script</dd>
<dt><kbd>text_gen_gpt2.py</kbd></dt><dd>is the launcher argument for the user script, specified in this case as the generation script</dd>
<dt><kbd>-d configs</kbd></dt><dd>is the launcher argument that specifies the directory where the configuration files are located</dd>
<dt><kbd>small.yml local_configs.yml</kbd></dt><dd>are the configuration files to use, in this case <samp>small.yml</samp> and <samp>local_configs.yml</samp> found within <samp>./configs/</samp>.</dt></dl></details>

**Comment by EinoHR** [comment]
Well, great.
Apparently I was too tired yesterday to _read properly_.
This issue can be safely closed now, even if I had another issue I wouldn't post it here.
