### ISSUE TITLE
ZeRO2 with Pipeline parallelism

### ISSUE THREAD

**Issue by hyunwoongko** [EleutherAI/gpt-neox#411]
I found out that the GPT-NeoX team has implemented pipeline parallelism with ZeRO2 (https://github.com/EleutherAI/gpt-neox/issues/62). Does this currently run efficiently? I'd love to hear about the current status of this work.

**Comment by hyunwoongko** [comment]
If you look [here](https://github.com/EleutherAI/DeeperSpeed/blob/main/deepspeed/runtime/pipe/engine.py#L63), it seems to be preventing the use of ZeRO2 and the pipeline engine together. Have you concluded that NeoX doesn't use ZeRO2 and pipeline parallelism together?

**Comment by hyunwoongko** [comment]
@stas00 I ping you because it's a topic that's fairly close to our work.

**Comment by hyunwoongko** [comment]
I found this https://github.com/microsoft/DeepSpeed/issues/823

**Comment by StellaAthena** [comment]
Hahaha yup. We basically went through that same process of thought four months ago.
