### ISSUE TITLE
Add NeoXArgs Documentation Generation to CI

### ISSUE THREAD

**Issue by sdtblck** [EleutherAI/gpt-neox#462]
We have a script [here](https://github.com/EleutherAI/gpt-neox/blob/main/configs/gen_docs.py) that auto-generates documentation for the neoxargs yml files, but no one has run it since it was added, and the docs have been out of date.

It would be a good idea to add the generation of docs to Continuous Integration, or I'm sure we'll forget to run it again for another few months

**Comment by slash-under** [comment]
This is currently being worked on in #595.
