### ISSUE TITLE
`cpu_offload` is depreciated

### ISSUE THREAD

**Issue by StellaAthena** [EleutherAI/gpt-neox#469]
**Describe the bug**
Running the model gives the following warning: `[2021-11-20 20:08:18,491] [WARNING] [config.py:77:_sanity_check] DeepSpeedConfig: cpu_offload is deprecated. Please use offload_optimizer. `

We should update the way that our code works to use the currently supported methodology.

**Comment by EricHallahan** [comment]
I actually have looked into this warning message on-and-off for a couple months now at a low priority as it has bugged me too. I'll assign myself to the task.

**Comment by Quentin-Anthony** [comment]
We can just remove the `cpu_offload` flags in the configs. DS has moved to `offload_optimizer` dicts (https://www.deepspeed.ai/docs/config-json/#optimizer-offloading) instead of a single `bool` anyway. I'll create a PR.
