### ISSUE TITLE
Ways to load GPT-NeoX checkpoints in GPT-Neo for TPU training?

### ISSUE THREAD

**Issue by frankxu2004** [EleutherAI/gpt-neox#475]
Thanks for the great project. I wonder if I could load the checkpoints for GPT-NeoX to GPT-Neo for the reason of leveraging TPU training. Or better yet does GPT-NeoX supports TPU training as well?

**Comment by StellaAthena** [comment]
There is not currently a supported way to convert GPT-NeoX checkpoints to GPT-Neo, and you cannot use GPT-NeoX on a large TPU cluster.

For training on TPUs I recommend checking out [mesh tensor Jax](http://www.GitHub.com/kingoflolz/mesh-tensor-had), the library that trained [GPT-J](https://huggingface.co/EleutherAI/gpt-j-6B).

**Comment by nikhilanayak** [comment]
Can GPT NeoX 20B be trained with Mesh Transformer JAX?
