### ISSUE TITLE
position embedding is not saved

### ISSUE THREAD

**Issue by eghbalhosseini** [EleutherAI/gpt-neox#495]
I am trying to recover position embedding for a trained model (rotary embedding) from the checkpoint folder, however its not in any of the pt files. how can I save position embedding?

**Comment by StellaAthena** [comment]
Rotary positional embeddings are calculated in advance. They do not change during training and therefore there's no need to save them.

**Comment by eghbalhosseini** [comment]
thanks, 
is there a tweak I can do in the code to save these during a checkpoint? or recreate them afterward. also is absolute positional embedding implemented in the pipeline ?

**Comment by StellaAthena** [comment]
Yes absolute positional embeddings is an option. You can check out `configs/neox_arguments.md` for more information.
