### ISSUE TITLE
error: could not create 'build/lib.linux-x86_64-3.7': Input/output error

### ISSUE THREAD

**Issue by OliveS9** [EleutherAI/gpt-neox#540]
How to fix the "error: could not create 'build/lib.linux-x86_64-3.7': Input/output error' when running "!python ./megatron/fused_kernels/setup.py install"? Thanks a lot!

**Comment by Mistobaan** [comment]
This is probably an issue with the linux environment / docker image. Your user doesn' thave permission to write on those folders.

**Comment by StellaAthena** [comment]
> `!python ./megatron/fused_kernels/setup.py install`

Are you running in a Colab by any chance? You cannot use the GPT-NeoX 20B model with a colab GPU or TPU instance.

**Comment by OliveS9** [comment]
How about on a paid GPU VM? Thanks.

**Comment by StellaAthena** [comment]
> How about on a paid GPU VM? Thanks.

That depends heavily on the GPU VM. Based on your questions however, I recommend considering simply paying a cloud provider for the model itself. There is very little reason for most users to try to deploy this model on their own.

**Comment by OliveS9** [comment]
But why does it not work on a VM with 4GPUs? Thanks.
