### ISSUE TITLE
Put Neo-X 20B weights on BitTorrent

### ISSUE THREAD

**Issue by depthwise** [EleutherAI/gpt-neox#542]
**Is your feature request related to a problem? Please describe.**
Currently, GPT Neo-X 20B weights take a loooong time to download even on a reasonably fast 200mbps fiber connection. 

**Describe the solution you'd like**
Could the authors please share them through Academic Torrents or as a direct Torrent download?

**Describe alternatives you've considered**
An alternative would be to maybe cache them through Cloudflare/Akamai I guess, but that's probably more expensive and less scalable for the purpose.

**Additional context**
Might be a good idea for other large downloads as well.

**Comment by StellaAthena** [comment]
How long does it take to download the weights on a 200 megabits per second internet connection? And are we talking about the full weights or the slim weights?

**Comment by depthwise** [comment]
To be clear, it's not realizing the full bandwidth of the connection. I haven't timed it, but wget command specified for slim weights showed something like 5MiB/sec earlier today. The total download size is 39GiB. so that's roughly two hours. This is on a connection that can normally can pull down at least 20MiB/sec. Here's the command I used to download:
```bash
wget --cut-dirs=5 -nH -r --no-parent --reject "index.html*" https://mystic.the-eye.eu/public/AI/models/GPT-NeoX-20B/slim_weights/ -P 20B_checkpoints
```
