### ISSUE TITLE
Error: scaled_upper_triang_masked_softmax.o: file not recognized

### ISSUE THREAD

**Issue by gitfan7** [EleutherAI/gpt-neox#544]
How to fix the error "gpt-neox/build/temp.linux-x86_64-3.7/content/gpt-neox/megatron/fused_kernels/scaled_upper_triang_masked_softmax.o: file not recognized: File format not recognized collect2: error: ld returned 1 exit status error: command 'x86_64-linux-gnu-g++' failed with exit status 1" when running "python ./megatron/fused_kernels/setup.py install"? Thanks a lot!

**Comment by StellaAthena** [comment]
This is an issue with your computer and the installed packages and not something we can help with or a problem with our code.
