### ISSUE TITLE
Implement Gradient Checkpointing

### ISSUE THREAD

**Issue by StellaAthena** [EleutherAI/gpt-neox#55]
Add the option to checkpoint gradients

**Comment by glebshevchukk** [comment]
Useful links for this:
https://github.com/microsoft/DeepSpeed/issues/63
https://github.com/microsoft/DeepSpeedExamples/blob/07d1ce0d26044602a7b8bb289e590a980f14aded/Megatron-LM/mpu/random.py

**Comment by sdtblck** [comment]
@StellaAthena deepspeed handles this implicitly from within the deepspeed config, doesn't need any implementation
