### ISSUE TITLE
Do you have a Jupyter Python notebook to showcase functionality or a Google Colab notebook?

### ISSUE THREAD

**Issue by shyamalschandra** [EleutherAI/gpt-neox#553]
Do you have a Jupyter Python notebook to showcase functionality or a Google Colab notebook?

**Comment by StellaAthena** [comment]
Are you asking about the library in general or the 20B model specifically? Either way the answer is no, but in the later case it’s actually impossible due to the lack of a powerful enough GPU via Collab.
