### ISSUE TITLE
error "megatron/fused_kernels/scaled_upper_triang_masked_softmax.o: file not recognized

### ISSUE THREAD

**Issue by OliveS9** [EleutherAI/gpt-neox#554]
The original folder of fused_kernels in the original package of Megatron-LM that NeoX uses does not have the file setup.py. Does anyone know which part of setup.py causes the error "megatron/fused_kernels/scaled_upper_triang_masked_softmax.o: file not recognized: File format not recognized collect2: error: ld returned 1 exit status error: command 'x86_64-linux-gnu-g++' failed with exit status 1"? Thanks a lot.

**Comment by StellaAthena** [comment]
You should not be using the original megatron-lm with any of our code.

**Comment by Mistobaan** [comment]
I suspect you are trying to compile this code on a platform other than linux
