### ISSUE TITLE
Request for help

### ISSUE THREAD

**Issue by aahad5555** [EleutherAI/gpt-neox#556]
so I am trying to pull out just embeddings from the model (slim weights), I just want output tensors, any guidance is much appreciated.

**Comment by rlabs-oss** [comment]
torch.load the checkpoint ?

`model_l0_s0 = torch.load("/SSD/gpt-neox/20B_checkpoints/global_step150000/layer_00-model_00-model_states.pt")

print(model_l0_s0)`

{'word_embeddings.weight': tensor([[-0.0009, -0.0013, -0.0020,  ...,  0.0002,  0.0002, -0.0009],
        [-0.0083, -0.0071, -0.0061,  ..., -0.0047,  0.0180, -0.0032],
        [-0.0001,  0.0071,  0.0208,  ...,  0.0162,  0.0078, -0.0239],
        ...,
        [-0.0051,  0.0345, -0.0181,  ..., -0.0161, -0.0211,  0.0027],
        [ 0.0273,  0.0025,  0.0333,  ..., -0.0264, -0.0252,  0.0109],
        [-0.0035,  0.0305,  0.0322,  ..., -0.0084, -0.0158,  0.0180]],
       dtype=torch.float16)}
