### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by OliveS9** [EleutherAI/gpt-neox#559]
How to fix the TypeError in "gpt-neox/megatron/fused_kernels/setup.py", line 11, in _get_cuda_bare_metal_version
    [cuda_dir + "/bin/nvcc", "-V"], universal_newlines=True
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str' when running "python ./megatron/fused_kernels/setup.py install" in README? Thanks.

**Comment by StellaAthena** [comment]
Try running
```
git checkout make_fused_kernels_optional
pip install -r requirements/requirements.txt
```
and then running the code you're interested in.

**Comment by OliveS9** [comment]
@StellaAthena    As I have tried your code, it shows the error below

```
"File "/usr/local/lib/python3.7/dist-packages/deepspeed/launcher/launch.py", line 147, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', 'generate.py',"
```

So how to fix it? Thanks!

**Comment by StellaAthena** [comment]
> @StellaAthena
> 
> As I have tried your code, it shows the error below
> 
> ```
> "File "/usr/local/lib/python3.7/dist-packages/deepspeed/launcher/launch.py", line 147, in sigkill_handler
>     raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
> subprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', 'generate.py',..."
> ```
> 
> So how to fix it? Thanks!

I have absolutely no idea. This doesn’t really provide a whole lot of information, and could easily be an issue with your local set-up rather than an issue with the code. It does look like my suggestion solved your original issue though?

**Comment by sharonzhou** [comment]
I'm also getting the original error :( And checking out the branch, installing requirements, and running it didn't work.

**Comment by sharonzhou** [comment]
It seems to be b/c nvcc is not installed, so running `sudo apt install nvidia-cuda-toolkit` will work, and then fused kernels can be installed (assuming compatible cuda versions)
