### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by Mather10** [EleutherAI/gpt-neox#561]
How to fix the error below

```
File "gpt-neox/megatron/tokenizer/tokenizer.py", line 39, in build_tokenizer
    assert args.vocab_file is not None
AssertionError
```

when running "./deepy.py generate.py ./configs/13B.yml"? Thanks.

**Comment by StellaAthena** [comment]
1. What are you expecting `./deepy.py generate.py ./configs/13B.yml` to do, exactly? We have not released a 13B parameter model. Do you have one sitting around you're planning on using?
2. To fix this error, you need to do exactly what it says: provide a vocab file
3. I strongly recommend you read the documentation of this GitHub repo before using it.
