### ISSUE TITLE
/usr/local/cuda-10.1/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version!`

### ISSUE THREAD

**Issue by OliveS9** [EleutherAI/gpt-neox#562]
How to fix the error 

`/usr/local/cuda-10.1/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version!`

when running "python megatron/fused_kernels/setup.py install"? Thanks.

**Comment by StellaAthena** [comment]
This is caused by you having out-of-date drivers on your system.
