### ISSUE TITLE
Issue on preconfiguring

### ISSUE THREAD

**Issue by Mather10** [EleutherAI/gpt-neox#567]
The Readme says "The tokenized data will be saved out to two files at [data-dir]/[dataset-name]/[dataset-name]_text_document.bin & [data-dir]/[dataset-name]/[dataset-name]_text_document.bin", but since [data-dir]/[dataset-name]/[dataset-name]_text_document.bin and [data-dir]/[dataset-name]/[dataset-name]_text_document.bin have the same file name and are under the same directory, then why are they two files? Thanks a lot.

**Comment by StellaAthena** [comment]
That’s a typo, one is saved with the extension `.idx` and the other `.bin`
