### ISSUE TITLE
Parallel all reduce communication and backprop

### ISSUE THREAD

**Issue by zhuzilin** [EleutherAI/gpt-neox#573]
Thank you for open source such a great repo for the community! Your work is really helping our team with training large pretrained model :)

In our experiment, we find out when training a not-that-large model, e.g. 2.7B, with data parallel, the scaling efficiency across multiple nodes is not good enough (under 70% for 2 nodes in our case). A reason for this is that currenly the backward calculation ("BackwardPass" instruction) and the communication (introduced in "ReduceGrads" instruction) are executed sequentially. In fact, if we start the allreduce communication right after each grad is calculated, we could parallel the backward computation and the ReduceGrads, reducing the negative effect on cross-node communication.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/10428324/155679102-452485fc-fc1d-4bfb-a921-34f988598624.png">

We could use the backward hook mechaism in pytorch for this optimization. [Here](https://github.com/pytorch/pytorch/blob/a6c6f42c255cb2b64ddd3119415d427072a7e7c4/torch/distributed/fsdp/fully_sharded_data_parallel.py#L917) is an example in the source code of pytorch.

This optimization may only work for pure data parallel as the communication pattern is quite different in model parallel or pipeline parallel.

We'd love to help if you have  interest in applying such optimization to your project (gpt-neox or DeeperSpeed)~ Thank you again for your great contribution to the community!

P.S. We found some different behavior compare to the comment here:
https://github.com/EleutherAI/gpt-neox/blob/f6c611f3211521fa7b145950ea100f44a2d0ead6/megatron/neox_arguments/arguments.py#L755-L758
- In our experiement, the `PipelineModule` wrapper is used when `pipe_parallel_size` is set to 1 and the `to_sequential()` version is used only when `pipe_parallel_size` is set to 0;
- The `PipelineModule` is observably faster than the `to_sequential()` version.

I wonder if these are expected behavior? Thank you.

**Comment by StellaAthena** [comment]
Very interesting! Can you upload the details about your cluster, namely the GPUs and interconnect being used, and the parallelism settings? I am surprised by this and want to do some experiments before making any changes.

re: your PS

I believe this was set up to do a comparative speed test of PP = 1 and sequential modeling, though I can’t find any records of the results of that testing. I’ll open a separate issue to test PP = 1 vs sequential so it doesn’t fall through the cracks again.

@EricHallahan I don’t suppose you recall or can find the results of this testing?

**Comment by EricHallahan** [comment]
> - In our experiement, the `PipelineModule` wrapper is used when `pipe_parallel_size` is set to 1 and the `to_sequential()` version is used only when `pipe_parallel_size` is set to 0;
> - The `PipelineModule` is observably faster than the `to_sequential()` version.
>
> I wonder if these are expected behavior? Thank you.

Yes, it is expected behavior. Setting `pipe_parallel_size` to <samp>0</samp> sets `is_pipe_parallel` to <samp>False</samp> and hence disables pipelining. This is needed because enabling pipelining has nontrivial memory overhead on some systems.

It is news to me that it is faster to use `PipelineModule` than `to_sequential()`, but that is because I do not personally recall any benchmarks or testing @StellaAthena.

**Comment by reyoung** [comment]
@StellaAthena Also, the NIC is 100G RDMA/RoCE.

**Comment by StellaAthena** [comment]
@ShivanshuPurohit is gong to look into this :)

@reyoung can you post whatever performance statistics you have? FLOPS, % comms, etc?

**Comment by StellaAthena** [comment]
In the original PR introducing the code you’re asking about, Sid also found that PP = 1 is faster than Sequential. He also doesn’t know why this is. https://github.com/EleutherAI/gpt-neox/pull/269

The desired behavior is for there to not be a sequential option. I’ll confirm that this isn’t what’s happening and patch it.
