### ISSUE TITLE
AttributeError: module 'yaml' has no attribute 'FullLoader'

### ISSUE THREAD

**Issue by OliveS9** [EleutherAI/gpt-neox#582]
How to fix the error 

```
/megatron/neox_arguments/arguments.py", line 158, in from_ymls
    conf = yaml.load(conf_file, Loader=yaml.FullLoader)
AttributeError: module 'yaml' has no attribute 'FullLoader'
```

when running "./deepy.py generate.py ./configs/20B.yml"? Thanks.

**Comment by StellaAthena** [comment]
Please try [Googling your question](https://www.google.com/search?q=module%20%27yaml%27%20has%20no%20attribute%20%27FullLoader%27&ie=utf-8&oe=utf-8&client=firefox-b-1-m) before opening more issues. Future errors that have nothing to do with our code and can be answered with a simple search will be treated as spam.
