### ISSUE TITLE
mlp.dense_4h_to_h.bias is useless with GPT-J residual

### ISSUE THREAD

**Issue by bellard** [EleutherAI/gpt-neox#584]
"mlp.dense_4h_to_h.bias" is useless when gpt_j_residual = true because "attention.dense.bias" plays the same role. So I suggest to remove either "mlp.dense_4h_to_h.bias" or "attention.dense.bias" when gpt_j_residual = true.

**Comment by StellaAthena** [comment]
Yes, we are aware. However implementing this has seemed like it’s more work than it’s worth and could negatively impact code readability and mantainability.
