### ISSUE TITLE
Gpt NeoX weights in HF and Fine tuning / inference colab notebook

### ISSUE THREAD

**Issue by sallumandya1995** [EleutherAI/gpt-neox#586]
I request the author / contributors to release HF Weights , and release notebook on inference and finetuning on Colab / AWS sagemaker studio.
Thanks and regards

**Comment by StellaAthena** [comment]
HF Weights will likely not be particularly helpful as HF doesn't currently support sufficient parallelism to use our pretrained model efficiently. That said, we are working with the HF team on this and they're independently working to make their codebase more efficient.

It is not possible to get enough compute in Google Colab to use this model. Similarly, unless SageMaker supports running on multiple GPUs it doesn't make sense to port it into their framework.

We highly recommend you use this codebase to do inference and our [Language Model Evaluation framework](https://github.com/EleutherAI/lm-evaluation-harness) to evaluate GPT-NeoX 20B.

**Comment by eghbalhosseini** [comment]
on that note, is it possible to add a benchmark to language Model evaluation framework to extraction hidden state and attention values for a user defined dataset?
