### ISSUE TITLE
Pretrained weights for smaller models

### ISSUE THREAD

**Issue by malteos** [EleutherAI/gpt-neox#598]
Thanks for this great project!

Are the pretrained weights for smaller models (e.g., those models listed in https://github.com/EleutherAI/gpt-neox/tree/main/configs) anywhere available for download?

**Comment by StellaAthena** [comment]
We have a 125M and 350M model [hosted on HuggingFace](https://huggingface.co/stellaathena) but we haven’t trained very many smaller models yet. That’s very much on the to-do list!
