### ISSUE TITLE
error: Cannot compile MPI programs

### ISSUE THREAD

**Issue by Mather10** [EleutherAI/gpt-neox#601]
How to fix the following error 

```
error: Cannot compile MPI programs. Check your configuration!!!
----------------------------------------
ERROR: Command errored out with exit status 1: /root/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] 
```

when running "pip install -r requirements/requirements.txt"? Thanks.

**Comment by StellaAthena** [comment]
`mpi4py` is a soft requirement that we haven’t gotten around to handling more elegantly. If you’re planning on using the torch distributed NCCL backend (which you probably should be), then you can delete this package requirement without breaking anything.
