### ISSUE TITLE
[BUG] Can't install dependencies.

### ISSUE THREAD

**Issue by 0x30c4** [EleutherAI/gpt-neox#602]
**Describe the bug**
To install the dependency I used ```pip install -r requirements/requirements.txt``` but it showed me 
this error message [error log](http://ix.io/3TRt) the last part of the error says 
```
× Encountered error while trying to install package.                                                                                                                                       
╰─> mpi4py                                                                                                                                                                                
```
So, I tried to install  it manually with ```pip install mpi3py```
But I got this [error](http://ix.io/3TRu) saying 
```
ERROR: Could not build wheels for mpi4py, which is required to install pyproject.toml-based projects
```
And then I installed the pyproject manually and got back to install mpi3py but failed.
I've no idea why it's happening.

**Environment (please complete the following information):**
 - GPUs: RTX 3090
- Configs: I'm using vast.ai's vastai/tensorflow 
- Python version is 3.9.6

**Comment by StellaAthena** [comment]
`mpi4py` is a soft requirement that we haven’t gotten around to handling more elegantly. If you’re planning on using the torch distributed NCCL backend (which you probably should be), then you can delete this package requirement without breaking anything.
