### ISSUE TITLE
Question: bias added on each node?

### ISSUE THREAD

**Issue by mickaelseznec** [EleutherAI/gpt-neox#615]
Hi, sorry it's more a question than a bug:

If I understand correctly, attention and MLP biases are added on each model-parallel node (see [here](https://github.com/EleutherAI/gpt-neox/blob/main/megatron/model/transformer.py#L607-L613) and [here](https://github.com/EleutherAI/gpt-neox/blob/main/megatron/model/transformer.py#L616-L623)).

Wouldn't that cause a problem when trying to use weights trained on 2 model-parallel GPUs with a 4 model-parallelism, for example? Biases would be added 4 times instead of 2. Of course, this could be fixed by scaling the biases according to the number of GPUs.

Is my reasoning correct, or am I missing something? Thanks :)

[EDIT]: From what I've understood, the situation is a little more subtle. Biases are different on each node. And that's also the case for the input_layernorm and post_attention_layernorm parameters (beta & gamma). What's the rationale behind not sharing those weights across all nodes?

[RE-EDIT]: Sorry I just found out about [merge20b.py](https://github.com/EleutherAI/gpt-neox/blob/8c978ff2dac9f1d86736d17054f1558cb0a36125/tools/merge20b.py). Looks like taking the average of the layernorm parameters was chosen. That should probably give good enough results but that's not mathematically equivalent, right?

**Comment by StellaAthena** [comment]
@zphang did a lot of this work and can speak to the particular details, but to address your question in the last edit
> [RE-EDIT]: Sorry I just found out about [merge20b.py](https://github.com/EleutherAI/gpt-neox/blob/8c978ff2dac9f1d86736d17054f1558cb0a36125/tools/merge20b.py). Looks like taking the average of the layernorm parameters was chosen. That should probably give good enough results but that's not mathematically equivalent, right?

You are correct that this is not mathematically equivalent. It has minimal performance loss compared to the original model though.

**Comment by mickaelseznec** [comment]
Ok, thanks for your answer!

In the future, I think having a model that doesn't depend on the number of GPUs it is instantiated on is desirable.
Sharing weights (bias & layernorm parameters) would unify the model without sacrificing expressiveness.
