### ISSUE TITLE
The training code hangs with multiple train_data_paths

### ISSUE THREAD

**Issue by sameeravithana** [EleutherAI/gpt-neox#621]
**Describe the bug**
I am testing the train.py code with multiple train_data_paths, specially 240 .bin and .idx files. Each .bin corresponds to maximum 1M docs. The code hangs right after printing the BlendedDataset index creation as in the screenshot below. The code hangs without any error. (> 1.5 days once)

**To Reproduce**
Have many data paths as input.
 
**Screenshots**

> RANK 5 elapsed time for building blendable dataset indices: 69.91 (sec)
> RANK 5 elapsed time for building blendable dataset indices: 0.01 (sec)
> RANK 5 elapsed time for building blendable dataset indices: 0.02 (sec)
> RANK 6 elapsed time for building blendable dataset indices: 69.95 (sec)
> RANK 6 elapsed time for building blendable dataset indices: 0.01 (sec)
> RANK 6 elapsed time for building blendable dataset indices: 0.02 (sec)
> RANK 7 elapsed time for building blendable dataset indices: 69.99 (sec)
> RANK 7 elapsed time for building blendable dataset indices: 0.01 (sec)
> RANK 7 elapsed time for building blendable dataset indices: 0.02 (sec)
> RANK 4 elapsed time for building blendable dataset indices: 70.05 (sec)
> RANK 4 elapsed time for building blendable dataset indices: 0.01 (sec)
> RANK 4 elapsed time for building blendable dataset indices: 0.02 (sec)
> RANK 1 elapsed time for building blendable dataset indices: 70.09 (sec)
> RANK 2 elapsed time for building blendable dataset indices: 70.10 (sec)
> RANK 1 elapsed time for building blendable dataset indices: 0.01 (sec)
> RANK 2 elapsed time for building blendable dataset indices: 0.01 (sec)
> RANK 1 elapsed time for building blendable dataset indices: 0.02 (sec)
> RANK 2 elapsed time for building blendable dataset indices: 0.02 (sec)
> RANK 3 elapsed time for building blendable dataset indices: 70.21 (sec)
> RANK 3 elapsed time for building blendable dataset indices: 0.01 (sec)
> RANK 3 elapsed time for building blendable dataset indices: 0.02 (sec)

**Environment (please complete the following information):**
 - GPUs: 8 GPUs
- Configs: XL.yml and local_*.yml

**Comment by StellaAthena** [comment]
Have you tried merging the files into one? 240 files is far beyond anything we've ever tested.

**Comment by sameeravithana** [comment]
@StellaAthena that is our next step, we can mitigate this issue with #files < 128. yet to find the reason behind that.

**Comment by sameeravithana** [comment]
@StellaAthena Is there a script to merge multiple .bin and .idx files?

**Comment by StellaAthena** [comment]
> @StellaAthena Is there a script to merge multiple .bin and .idx files?

Not currently, no. You can concatenate the text files and reprocess, but I would have to look into the data loading code (which I haven’t looked at in close to a year) to see about merging existing files

**Comment by StellaAthena** [comment]
Closing as we don’t intend on addressing this any time soon.
