### ISSUE TITLE
Off by one bug in generate_samples_interactive

### ISSUE THREAD

**Issue by fpgaminer** [EleutherAI/gpt-neox#627]
The `generate_samples_interactive` function has an off-by-one error that means it drops the last token every time.  See here: https://github.com/EleutherAI/gpt-neox/blob/6a76fe6a8011d6c9b9d44e55a1ade59755dd0435/megatron/text_generation_utils.py#L767-L771

It should be `batch_token_generation_end_index[0].item() + 1`.

`generate_samples_from_prompt` does it correctly; see: https://github.com/EleutherAI/gpt-neox/blob/6a76fe6a8011d6c9b9d44e55a1ade59755dd0435/megatron/text_generation_utils.py#L508

**Comment by StellaAthena** [comment]
Thanks for the bug report! I have implemented the patch [here](https://github.com/EleutherAI/gpt-neox/pull/629) and would be much obliged if you could check if it’s working as intended
