### ISSUE TITLE
wget download weights not working

### ISSUE THREAD

**Issue by Slim0120** [EleutherAI/gpt-neox#646]
Hello,

When I tried downloading the slim weights using wget, python kept saying it could not connect to server. I tried using torrent method of download, and it could not connect to server either. Please let me know if there is other way to downloading the weights.

**Comment by rujiewu** [comment]
I had the same problem as you, tried for hours and still failed.

**Comment by rujiewu** [comment]
Replace the link with [this](https://the-eye.eu/public/AI/models/GPT-NeoX-20B/slim_weights/) and it will work.
Old [link](https://mystic.the-eye.eu/public/AI/models/GPT-NeoX-20B/slim_weights/) is dead.

**Comment by Slim0120** [comment]
It works now, thank you!

**Comment by StellaAthena** [comment]
The links in the readme have been fixed
