### ISSUE TITLE
on training tokens of gpt-neox-20b and gpt-j-6b

### ISSUE THREAD

**Issue by xiaoda99** [EleutherAI/gpt-neox#654]
[The paper](https://arxiv.org/pdf/2204.06745.pdf) memtioned:
"To achieve a higher training throughput, we opt to use the same batch size as OpenAI’s 175B model–approximately 3.15M tokens, or 1538 contexts of 2048 tokens each, and train for a total of 150,000 steps"
So the total number of training tokens is: 3.15M * 150,000 = 472G. right?
This number is much s smaller than other LLMs, e.g. GPT-3 (300B), BERT (200B), RoBERTa (2000B).

It is also much smaller than GPT-J-6B.  [the blog](https://arankomatsuzaki.wordpress.com/2021/06/04/gpt-j/) reported that:
"The model was trained on 400B tokens from [The Pile](https://pile.eleuther.ai/) dataset with 800GB text."
But there I'm also confused about how this figure is computed:
(also in the blog) "Throughput of the 6B GPT-J for training (151k tokens/s) is faster than the 2.7B GPT-Neo (148k tokens/s) on the same hardware (TPU v3-256 pod)", "GPT-J training took roughly five weeks with TPU v3-256."
So shoudn't it be 151k * 3600 * 24 * 7 * 5  = 456G?

Where am I wrong? It gpt-neox-20b and gpt-j-6b were trained with 1000 times fewer tokens, how could they achieve comparable or better eval results than gpt-3 curie with similar model size?

**Comment by davidsj** [comment]
If I understand your question, the confusion is that the "B" suffix in e.g. "300B", "200B", "2000B" does not mean 10^12. It means 10^9.

"Billion", in some English dialects and some other languages, means 10^12. But usually, and here, it means 10^9, like "giga" / "G".

Sorry if I've misunderstood you.

**Comment by xiaoda99** [comment]
got it. solved my confusion completely. thx !
