### ISSUE TITLE
Decentrealized Model Training Via Volunteer grid GPU/CPU computing with BOINC

### ISSUE THREAD

**Issue by rugabunda** [EleutherAI/gpt-neox#655]
**Is your feature request related to a problem? Please describe.**

Given independent AI production resources are limited in scope compared to black box big tech platforms,  an open, collaborative machine learning platform training models through a global volunteer grid of computing power will elevate opensource ai to the parameter level of GPT3 and beyond in short order.

**Describe the solution you'd like**
BOINC is open source open cloud computing software allowing developers to decentralize and streamline heavy computer workloading similar to that of torrenting. Utilizing this platform we can speed up the processing of machine learning model data by leveraging a global network of volunteer processing power, unleashing the most powerful opensource AI available to the public realm.

Is there any plans already in place to implement this, and if not, what are your greatest ideas on making this a reality?

**Comment by davidsj** [comment]
There's some discussion of this [here](https://www.eleuther.ai/faq/).
