### ISSUE TITLE
How to save position embedding?

### ISSUE THREAD

**Issue by cdj0311** [EleutherAI/gpt-neox#661]
hi,
   I cannot found a position embedding file in saved model, how to save or calculate?
thanks!

**Comment by StellaAthena** [comment]
The checkpointing code does not explicitly save positional embeddings. What are you looking to achieve?

**Comment by cdj0311** [comment]
> The checkpointing code does not explicitly save positional embeddings. What are you looking to achieve?

I want use FasterTransformer to speed up inference, but FasterTransformer need position embedding table, the shape is [max_seq_len, hidden_units]
