### ISSUE TITLE
Intermittent error while running ./deepy.py generate.py ./configs/20B.yml -i <input> -o output

### ISSUE THREAD

**Issue by pujari-rajkumar** [EleutherAI/gpt-neox#675]
Hi,

    I get this error while running generation from a file. I get this error for some examples, for some I don't. I have 4 Nvidia 1080 Ti GPUs with cuda version 10.2, pytorch version 1.12.1. 

Entire output on the command line is here: https://docs.google.com/document/d/1YnVHPLvbl_-7IZH5my7g1TTE9bK1S-xg8G1YAyICC3E/edit?usp=sharing

The input file generating the error is here: https://docs.google.com/document/d/11-EalnBqtATeUBmC_mQwIJRp9P2Mmct1jHPK1Ga4dbE/edit?usp=sharing

Also, here's a prompt that doesn't give any error: https://docs.google.com/document/d/1YgIfPjX6jJWjxNN9GKH9Qk6jNUeUn4TmD6YiqsmIWTg/edit?usp=sharing

And a small prompt that does: https://docs.google.com/document/d/17VdEevi5wRkcBjR8T-9shkygWAbRf6zQ2nVcyUC9pBU/edit?usp=sharing

Could someone please help me? Thank you in advance!

**Comment by pujari-rajkumar** [comment]
Anyone?

**Comment by StellaAthena** [comment]
> Did anyone get a chance to look at this issue? @StellaAthena

Do you have an English text that causes this error? This model was trained to be a monolingual English model and support for prompting or finetuning with other languages is not supported.

**Comment by pujari-rajkumar** [comment]
Ohh, I just assumed it was multi-lingual, my mistake. So far none of the English prompts caused this issue. Thanks a lot for clarifying!

**Comment by pujari-rajkumar** [comment]
Hi @StellaAthena I have an English input file that also generates the same error: https://docs.google.com/document/d/13uChzEtgay0wuh1tZpGadBTdN0_IBNerKc2J-DrEZbY/edit?usp=sharing

The log of this run is here: https://docs.google.com/document/d/1IZe-J2hsv021ShPhOLB8MJJPVmTNvNSmC3iVMJD7bmo/edit?usp=sharing

**Comment by pujari-rajkumar** [comment]
@StellaAthena Here's a small English prompt that gives the same error: https://docs.google.com/document/d/1x6lbmV1YgoL1LcaBjG3h4QZzCNigZAgo_fThXAE8trM/edit?usp=sharing

And its corresponding log: https://docs.google.com/document/d/1AwgSK_JMA6PaW5QxLigm4-AgFOElH_XReoKP73cMYKc/edit?usp=sharing

**Comment by pujari-rajkumar** [comment]
Also, here's a bunch of 386 English prompts with their outputs, logs and error status for debugging.

[paraphrase_prompts.zip](https://github.com/EleutherAI/gpt-neox/files/9674370/paraphrase_prompts.zip)

**Comment by pujari-rajkumar** [comment]
@haileyschoelkopf @lintangsutawika @AranKomat Could one of you help me please?
