### ISSUE TITLE
Parameter Sharing in NeoX

### ISSUE THREAD

**Issue by StellaAthena** [EleutherAI/gpt-neox#685]

**Comment by haileyschoelkopf** [comment]
https://github.com/EleutherAI/gpt-neox/tree/t5-shared-params <- WIP implementation in this branch. Pending preliminary experiment from Adam to continue working on this

**Comment by StellaAthena** [comment]
@haileyschoelkopf should I close this as abandoned?

**Comment by haileyschoelkopf** [comment]
Yup, this was for the Improved-T5 project.
