### ISSUE TITLE
Sample efficiency experiment

### ISSUE THREAD

**Issue by AranKomat** [EleutherAI/gpt-neox#689]
As in the original T5 paper, we train T5 (and GPT for reference) with a varying number of epochs (e.g. 1, 8, 64, etc) on C4 and see at which point test perplexity and SuperGLUE score degrades noticeably from that of the one epoch training. We also vary the size of the model (e.g. Base, Large, XL for 128B tokens) to see how the threshold moves w.r.t. the model size.

**Comment by StellaAthena** [comment]
Closing as we are not currently planning on implementing encoder-decoder models
