### ISSUE TITLE
SuperGLUE / multitask finetuning

### ISSUE THREAD

**Issue by lintangsutawika** [EleutherAI/gpt-neox#690]

**Comment by lintangsutawika** [comment]
Implementation here: https://github.com/EleutherAI/gpt-neox/pull/676

**Comment by lintangsutawika** [comment]
@haileyschoelkopf I can also test this and make sure P3 is also compatible.

**Comment by haileyschoelkopf** [comment]
Adding P3 would be super helpful!! I can tackle Bigbench lite, potentially.

**Comment by lintangsutawika** [comment]
Alright, will do.

**Comment by lintangsutawika** [comment]
Close for now as we have switched to T5X for this project.
