### ISSUE TITLE
Scaling experiment

### ISSUE THREAD

**Issue by AranKomat** [EleutherAI/gpt-neox#694]
I will use our own scale of models instead of Base, Large, etc, of T5, as we want to explore the depth-to-width ratios for optimal performance in Phase I. I will train models from 200M to ~3B for 32B tokens or so to find the best ratio.

Then, I will train the models with the optimal ratio and size from 200M to ~3B for 128B tokens, multitask finetune them at various checkpoints to draw training curves on perf vs. FLOPS log-log plot to find the optimal model-size vs. num_tokens ratio.

**Comment by StellaAthena** [comment]
Closing as we are not currently planning on implementing encoder-decoder models
