### ISSUE TITLE
Support Promptsource-integrated evaluation in NeoX `evaluate.py` / `eval_adapter.py`

### ISSUE THREAD

**Issue by haileyschoelkopf** [EleutherAI/gpt-neox#696]

**Comment by StellaAthena** [comment]
What specifically do we wish to support? Loading the models? Something else?

**Comment by haileyschoelkopf** [comment]
Ah apologies thought that I linked #697 to this! Will make the issue title more descriptive

We wanted to be able to run NeoX's `evaluate.py` using the Promptsource-integrated fork so that we could evaluate on whatever prompt we wanted, e.g. for SuperGLUE T5's prompts or for P3 datasets if we do multitask finetuning in NeoX.

This might not be immediately relevant if we can get t5x on GPU working though.

**Comment by StellaAthena** [comment]
Preempted by up streaming prompted evaluation in the Eval Harness.
