### ISSUE TITLE
Intermittent error while running ./deepy.py generate.py ./configs/20B.yml -i <input> -o <output>

### ISSUE THREAD

**Issue by pujari-rajkumar** [EleutherAI/gpt-neox#700]
**Describe the bug**
Cuda: kernel image not found error when running generation

**To Reproduce**
./deepy.py generate.py ./configs/20B.yml -i <input> -o <output>
with this prompt: https://docs.google.com/document/d/13uChzEtgay0wuh1tZpGadBTdN0_IBNerKc2J-DrEZbY/edit?usp=sharing
Smaller troublesome prompt: https://docs.google.com/document/d/1x6lbmV1YgoL1LcaBjG3h4QZzCNigZAgo_fThXAE8trM/edit?usp=sharing

**Expected behavior**
Output log of the first prompt: https://docs.google.com/document/d/1IZe-J2hsv021ShPhOLB8MJJPVmTNvNSmC3iVMJD7bmo/edit?usp=sharing
Output log for smaller prompt: https://docs.google.com/document/d/1AwgSK_JMA6PaW5QxLigm4-AgFOElH_XReoKP73cMYKc/edit?usp=sharing

**Environment (please complete the following information):**
 - GPUs: 4  Nvidia 1080 Ti GPUs
- Configs: Here's my environment package list: https://docs.google.com/document/d/1Kw8QqIxxjToT0lHAKmi_SAIt4CkNn1ZzGyoNyj4Zk_E/edit?usp=sharing
- PyTorch: 1.12.1, Cuda: 11.3, python: 3.8.13, cudatoolkit: 11.3.1

**Additional context**
Additional prompts, outputs and their logs of the runs here: https://github.com/EleutherAI/gpt-neox/files/9674370/paraphrase_prompts.zip
Status of each prompt's run is in the status.json file

**Comment by pujari-rajkumar** [comment]
@StellaAthena @AranKomat Could you kindly help me?

**Comment by StellaAthena** [comment]
I’m sorry you’ve been having trouble with this. We are aware of the issue but do not have the personnel to prioritize patching this at this time. At this time I recommend using the HuggingFace `transformers` library for inference, or the hosted web demo at 20b.eleuther.ai.

If you are interested in developing and contributing a patch, we would be ecstatic to merge it into `main` to prevent others from struggling with this.

**Comment by pujari-rajkumar** [comment]
I couldn't figure out the exact issue but I realized that it is because of the older GPUs. I moved to another cluster with Tesla V100 and A5000 GPUs and this error doesn't appear. I have seen the same issue in other repos and the usual suggestion that worked for them is to build PyTorch from scratch for their machine rather than installing it from the pre-compiled binaries from the website.

**Comment by StellaAthena** [comment]
Ah curious. We haven't tested this codebase at all on GPUs other than Volta and Ampere series, so that's really not surprising. Since updating to one of the supported hardwares fixes the problem, I'm going to close this issue and consider it completed.
