### ISSUE TITLE
Distill GPT-Neo

### ISSUE THREAD

**Issue by akul-goyal** [EleutherAI/gpt-neox#705]
**Is your feature request related to a problem? Please describe.**
My feature request is not related to a problem. Is there a plan to ever get GPT-Neo distilled?

**Describe the solution you'd like**
Distill any of the GPT-Neo Models. 

**Describe alternatives you've considered**
I considered doing it on my own however saw that the authors of this repo tried to do so already and were unable. 

**Additional context**
The code I was planning on using heavily borrows from [this](https://towardsdatascience.com/distillation-of-bert-like-models-the-code-73c31e8c2b0a) medium article.

**Comment by StellaAthena** [comment]
You're welcome to try, but we don't have any specific plans to do this after failing to make it work for months.

**Comment by akul-goyal** [comment]
I apologize, I should have written the issue more clearly. I tried to read the past issues about distilling the model and it was not clear why model distillation was not working. Was it the loss function that prevented the distillation?
