### ISSUE TITLE
Hardware required for fine-tuning GPT-NeoX-20B

### ISSUE THREAD

**Issue by jennyzzt** [EleutherAI/gpt-neox#707]
What is the hardware and speed for the person fine-tuning the 20B parameter model above?

I am interested in using GPT-NeoX-20B for fine-tuning. Would 2 servers of 8 A100s GPU be sufficient? From your repo, the model weights and optimizer states are a total size of 268GB. My intuition is that since 2 servers of 8 A100 GPUs has a total memory of 1280GB, it should be more than enough. However, given the relatively large embedding and lm-head layers, I wonder if it will be sufficient?

_Originally posted by @jennyzzt in https://github.com/EleutherAI/gpt-neox/issues/409#issuecomment-1289812711_

**Comment by StellaAthena** [comment]
Yes, I would expect this to work. Speed depends on your exact hardware set-up, so I can't really comment on that.

**Comment by chuanli11** [comment]
As a reference point I was able to get 20B model training started on [three 8xA100 40GB servers](https://github.com/LambdaLabsML/examples/blob/main/gpt-neox-training/README.md#train-20b-model). 

Need to set `pipe-parallel-size` to 6, and `model-parallel-size` to 4, otherwise it will OOM.
