### ISSUE TITLE
gpt3small is broken

### ISSUE THREAD

**Issue by StellaAthena** [EleutherAI/gpt-neox#71]
gpt3small seems to have been left behind in some of our updates, and neither `scripts/train_gpt3small.sh` nor `scripts/train_gpt3small_pipeline.sh` run.

**Comment by srulikbd** [comment]
`scripts/train_gpt3small.sh` is running at my colab (I only dropped the train batch size because of OOM)..

**Comment by StellaAthena** [comment]
> `scripts/train_gpt3small.sh` is running at my colab (I only dropped the train batch size because of OOM)..

Interesting. Can you provide a link to the file?

**Comment by srulikbd** [comment]
https://colab.research.google.com/drive/1IThG90kOdndybKuScNEZ1QG9nwnuj2l1?usp=sharing
there is some problem with the pipeline code. I'm trying fixing it. something with 
`num_stages (2) must divide distributed world size (1)`

**Comment by StellaAthena** [comment]
Ah yes, you cannot use parallel pipeline on a single GPU unit. The whole
point of parallel pipeline is to divide the pipeline between GPUs, which
you cannot do. You can manually set num_stages to 1, or you can use the
non-pipeline code.

**Comment by srulikbd** [comment]
ok, what I suspected. thanks!
how can I help right now?
I saw that we need kubernetes skills, so I'm learning it.
anything else for a newcomer?

**Comment by StellaAthena** [comment]
Have you checked out the [Evaluation Harness](
https://github.com/EleutherAI/lm-evaluation-harness)? That is extremely
important to both this project and other ones, and is more accessible to
people who can write code but are newcomers to AI research. Each task that
needs completing has an associated Issue.
