### ISSUE TITLE
Broken "learned" embeddings

### ISSUE THREAD

**Issue by Quentin-Anthony** [EleutherAI/gpt-neox#721]
This PR (https://github.com/EleutherAI/gpt-neox/commit/7c25eed8a8d5a6a87560370f2a6187f138eca0af#diff-5ae2f919cc2b3b2cf7bc8193b6e1c1cfd2e9c15d75edcb44b213ccc80b772110R122) breaks "learned" embeddings with:

```
  File "/fsx/quentin/gpt-neox/megatron/model/utils.py", line 187, in forward
    x = exec_range_func(start_idx, end_idx)(*x)
  File "/fsx/quentin/gpt-neox/megatron/model/utils.py", line 160, in exec_func
    inputs = layer(inputs)
  File "/fsx/quentin/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/fsx/quentin/gpt-neox/megatron/model/word_embeddings.py", line 162, in forward
    embeddings = super().forward(input_ids, position_ids)
  File "/fsx/quentin/gpt-neox/megatron/model/word_embeddings.py", line 124, in forward
    position_ids = position_ids + self.layer_past + 1
RuntimeError: The size of tensor a (2048) must match the size of tensor b (4) at non-singleton dimension 1
```

Can be replicated with 125M.yml local_setup.yml and enron on a single node, but I assume most configs will set it off. Reverting https://github.com/EleutherAI/gpt-neox/commit/7c25eed8a8d5a6a87560370f2a6187f138eca0af#diff-5ae2f919cc2b3b2cf7bc8193b6e1c1cfd2e9c15d75edcb44b213ccc80b772110R121-R129 resolves the issue.

**Comment by StellaAthena** [comment]
@Quentin-Anthony did you test if the OPT-style positional embeddings still work with your fix? Personally, I’m not particularly attached to allowing people to use them, but if they don’t we should probably just remove the config entirely.

Tagging @zphang for visibility

**Comment by Quentin-Anthony** [comment]
> @Quentin-Anthony did you test if the OPT-style positional embeddings still work with your fix? Personally, I’m not particularly attached to allowing people to use them, but if they don’t we should probably just remove the config entirely.
> 
> Tagging @zphang for visibility

My naive fix would be to just wrap the code snippet I linked in an `if self.opt_pos_emb_offset`. That shouldn't break OPT, but I'm not sure how to correctly test "OPT with gpt-neox" to be honest.

@zphang -- I'm going to create a PR with my proposed fix. Can you test it out with an OPT model?

**Comment by StellaAthena** [comment]
> My naive fix would be to just wrap the code snippet I linked in an `if self.opt_pos_emb_offset`. That shouldn't break OPT, but I'm not sure how to correctly test "OPT with gpt-neox" to be honest.

Yeah, I’m in the same boat (for one, I don’t have OPT checkpoints that load in NeoX…) else I would have done it myself. We’ll see what Jason says
