### ISSUE TITLE
Model ckpts from `DeeperSpeed` cannot be loaded using `deepspeed_main`/upstream DeepSpeed

### ISSUE THREAD

**Issue by haileyschoelkopf** [EleutherAI/gpt-neox#732]
**Describe the bug**

Using DeeperSpeed-trained model checkpoints (git+https://github.com/EleutherAI/DeeperSpeed.git@eb7f5cff36678625d23db8a8fe78b4a93e5d2c75#egg=deepspeed
), 

loading them raises an error when trying to use `deepspeed_main` with the upstream DeepSpeed.

**To Reproduce**

Train a model from `main` branch using DeeperSpeed (or download model ckpt from `s-eai-neox/pythia/1.3B/global_step71500`)

Try to load this checkpoint using the `deepspeed_main` branch and upstream Deepspeed (for either training or evaluation), gives the following error:
```
Traceback (most recent call last):
  File "/fsx/hailey/deepspeed-main-neox/gpt-neox/evaluate.py", line 76, in <module>
    main()
  File "/fsx/hailey/deepspeed-main-neox/gpt-neox/evaluate.py", line 35, in main
    model, neox_args = setup_for_inference_or_eval(use_cache=False)
  File "/fsx/hailey/deepspeed-main-neox/gpt-neox/megatron/utils.py", line 440, in setup_for_inference_or_eval
    model, _, _ = setup_model_and_optimizer(
  File "/fsx/hailey/deepspeed-main-neox/gpt-neox/megatron/training.py", line 437, in setup_model_and_optimizer
    neox_args.iteration = load_checkpoint(
  File "/fsx/hailey/deepspeed-main-neox/gpt-neox/megatron/checkpointing.py", line 235, in load_checkpoint
    checkpoint_name, state_dict = model.load_checkpoint(
  File "/fsx/shiv/torchtest/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 2647, in load_checkpoint
    load_path, client_states = self._load_checkpoint(load_dir,
  File "/fsx/shiv/torchtest/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 2713, in _load_checkpoint
    self.load_module_state_dict(state_dict=checkpoint['module'],
  File "/fsx/shiv/torchtest/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 2507, in load_module_state_dict
    self.module.load_state_dict(state_dict, # TODO
  File "/fsx/shiv/torchtest/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1620, in load_state_dict
    raise TypeError("Expected state_dict to be dict-like, got {}.".format(type(state_dict)))
TypeError: Expected state_dict to be dict-like, got <class 'NoneType'>.
```
This gives the above traceback and checkpoint loading fails.

**Expected behavior**
The checkpoints should be loadable by either Deepspeed version, ideally.

**Proposed solution**
This could be an issue with Deepspeed checkpoint formats changing over the course of 4 versions--not sure yet.

**Additional context**
Relevant to merging #663 since we have checkpoints we want to use trained in DeeperSpeed.

cc @Quentin-Anthony @dashstander @StellaAthena

**Comment by Quentin-Anthony** [comment]
I don't think this is possible due to the zero changes in DS `0.3.17`:

https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/zero/stage_1_and_2.py#L2314-L2317

I think we should just add a disclaimer to the gpt-neox release README that any old checkpoints must be loaded with legacy DeeperSpeed. 

@StellaAthena and @haileyschoelkopf -- Thoughts?

**Comment by haileyschoelkopf** [comment]
Ah darn, was worried this was a DS breaking change. I think that makes sense to me! if people need to use the old version they can still do that.

**Comment by StellaAthena** [comment]
> I think we should just add a disclaimer to the gpt-neox release README that any old checkpoints must be loaded with legacy DeeperSpeed.

I think this makes sense. There’s a library release that freezes GPT-NeoX at a point that’s compatible with the original checkpoints [here](https://github.com/EleutherAI/gpt-neox/releases/tag/legacy_gptj_residual.1.0.0). If we can do the same with DeeperSpeed and explain that briefly I think we’ll be good to go.

**Comment by haileyschoelkopf** [comment]
Closing now that we have an updated script to use for v2.0!
