### ISSUE TITLE
distributed training with multipy nodes.

### ISSUE THREAD

**Issue by cdj0311** [EleutherAI/gpt-neox#734]
Hi, 
    I want train a 13B model with 4 nodes, each node have 8*A100 GPUs, but I don't know how to run the code on my cluster, can you show me an example? I just run it on a single node successful.

**Comment by StellaAthena** [comment]
What is the command that is successfully launching training on a single node? And can you post your hostfile (or equivalent)?

It _should_ parallelize across nodes automatically…

**Comment by cdj0311** [comment]
> What is the command that is successfully launching training on a single node? And can you post your hostfile (or equivalent)?
> 
> It _should_ parallelize across nodes automatically…

I don't know how to use the hostfile, training on a single node: **python ./deepy.py ./train.py ./configs/125M.yml**, can you post an example of hostfile?

**Comment by StellaAthena** [comment]
Yes, that's correct. What cluster management system do you use? Kubernetes? SLURM? Something else?

**Comment by cdj0311** [comment]
> Yes, that's correct. What cluster management system do you use? Kubernetes? SLURM? Something else?

Kubernetes.

**Comment by cdj0311** [comment]
@StellaAthena I use this repo Dockerfile to run, but get an ssh error as follows:
````
172.17.0.2: Permission denied, please try again.
172.17.0.3: Permission denied, please try again.
172.17.0.2: Permission denied, please try again.
172.17.0.3: Permission denied, please try again.
172.17.0.2: mchorse@172.17.0.2: Permission denied (publickey,password).
pdsh@6dca91c32bfd: 172.17.0.2: ssh exited with exit code 255
172.17.0.3: mchorse@172.17.0.3: Permission denied (publickey,password).
pdsh@6dca91c32bfd: 172.17.0.3: ssh exited with exit code 255
````

The hostfile:
````
172.17.0.2 slots=1
172.17.0.3 slots=1
````

Run commad:
````
python ./deepy.py ./train.py ./configs/125M.yml ./configs/local_setup.yml --hostfile hostfile
````
local_setup.yml
````
{
  "data-path": "train_text_document",
  "num_nodes":2,
  "vocab-file": "vocab.json",
  "merge-file": "merges.txt",
  "save": "checkpoints",
  "load": "checkpoints",
  "checkpoint_validation_with_forward_pass": False,
  "tensorboard-dir": "tensorboard",
  "log-dir": "logs",
  "use_wandb": True,
  "wandb_host": "https://api.wandb.ai",
  "wandb_project": "neox"
}
````

**Comment by StellaAthena** [comment]
Hmmm that’s strange. I can see a couple problems off the bat:
1. It thinks there’s two nodes, not four
2. It thinks every node has one GPU, not eight
3. Passwordless ssh isn’t being set-up properly (that’s what’s giving the actual error)

What if you use the Dockerfile located on DockerHub at `leogao2/gpt-neox`? Does that change anything?

**Comment by cdj0311** [comment]
> Hmmm that’s strange. I can see a couple problems off the bat:
> 
> 1. It thinks there’s two nodes, not four
> 2. It thinks every node has one GPU, not eight
> 3. Passwordless ssh isn’t being set-up properly (that’s what’s giving the actual error)
> 
> What if you use the Dockerfile located on DockerHub at `leogao2/gpt-neox`? Does that change anything?

1-2, I just test on two local machine now.
I build the docker with https://github.com/EleutherAI/gpt-neox/blob/main/Dockerfile, and nothing has changed.

**Comment by StellaAthena** [comment]
What if you use the Dockerfile located on DockerHub at leogao2/gpt-neox?

**Comment by cdj0311** [comment]
> What if you use the Dockerfile located on DockerHub at leogao2/gpt-neox?

I use the lastest Docker Image from leogao2/gpt-neox:sha-96212f8, but get the same error.

Is the hostfile necessary? Can I just write master_addr and master_port like torch.distributed.launch?

**Comment by WaveLi123** [comment]
> > What if you use the Dockerfile located on DockerHub at leogao2/gpt-neox?
> 
> I use the lastest Docker Image from leogao2/gpt-neox:sha-96212f8, but get the same error.
> 
> Is the hostfile necessary? Can I just write master_addr and master_port like torch.distributed.launch?

I have met the same problem, how's your final solution?

**Comment by SefaZeng** [comment]
Any new developments? Struggling with distributed training...

**Comment by macabdul9** [comment]
Hi @StellaAthena 

Do you have any resources on how to run multi-node training using `SLURM`?

**Comment by mwy691222563** [comment]
Can I just write master_addr and master_port like torch.distributed.launch?

**Comment by dingning97** [comment]
> Can I just write master_addr and master_port like torch.distributed.launch?

have you solved this? How to write master_addr and master_port like torch.distributed.launch to train on multiple nodes?
