### ISSUE TITLE
Issue deploying GPT-NeoX-20b on AWS Sagemaker with Jupyter Notebook

### ISSUE THREAD

**Issue by BjornTheProgrammer** [EleutherAI/gpt-neox#740]
**Describe the bug**
I get the following error upon trying to use `predictor.predict(data)` for AWS Sagemaker.
```pytb
ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (400) from primary with message "{
  "code": 400,
  "type": "InternalServerException",
  "message": "Could not load model /.sagemaker/mms/models/EleutherAI__gpt-neox-20b with any of the following classes: (\u003cclass \u0027transformers.models.auto.modeling_auto.AutoModelForCausalLM\u0027\u003e, \u003cclass \u0027transformers.models.gpt_neox.modeling_gpt_neox.GPTNeoXForCausalLM\u0027\u003e)."
}
```

**To Reproduce**
1. Create Dockerfile
2. Add the following into Dockerfile
```
FROM 763104351884.dkr.ecr.us-east-1.amazonaws.com/huggingface-pytorch-inference:1.10.2-transformers4.17.0-gpu-py38-cu113-ubuntu20.04
RUN pip install --upgrade 'transformers==4.25.1'
RUN pip install --upgrade 'torch==1.13.0'
```
3. Build the Dockerfile via command `docker build -t gpt-neox .` in the directory Dockerfille is in
4. Create a file named `dockerize.sh`
5. Add the following content into the file
```bash
%%sh

# Specify an algorithm name
algorithm_name=gpt-neox

account=$(aws sts get-caller-identity --query Account --output text)

# Get the region defined in the current configuration (default to us-west-2 if none defined)
region=$(aws configure get region)

fullname="${account}.dkr.ecr.${region}.amazonaws.com/${algorithm_name}:latest"

# If the repository doesn't exist in ECR, create it.

aws ecr describe-repositories --repository-names "${algorithm_name}" > /dev/null 2>&1
if [ $? -ne 0 ]
then
aws ecr create-repository --repository-name "${algorithm_name}" > /dev/null
fi

# Log into Docker
aws ecr get-login-password --region ${region}|docker login --username AWS --password-stdin ${fullname}

# Build the docker image locally with the image name and then push it to ECR
# with the full name.

docker build -t ${algorithm_name} .
docker tag ${algorithm_name} ${fullname}

docker push ${fullname}
```
7. Run command `docker login` (you need docker cli)
8. Execute the shell script file (you need aws cli)
10. Open Jupyter Notebook 
11. Add the following to Jupyter Notebook
```python
%pip install sagemaker
%pip install boto3
```
```python
from sagemaker.huggingface import HuggingFaceModel
import boto3

client=boto3.client('sts')
account=client.get_caller_identity()['Account']

my_session=boto3.session.Session()
region=my_session.region_name

algorithm_name="gpt-neox"
tag="latest"
ecr_image='{}.dkr.ecr.{}.amazonaws.com/{}:{}'.format(account, region, algorithm_name, tag)

role = 'SageMaker'

hub = {
    'HF_MODEL_ID':'EleutherAI/gpt-neox-20b',
    'HF_TASK':'text-generation'
}

huggingface_model = HuggingFaceModel(
    image_uri=ecr_image,
    env=hub,
    role=role,
#     transformers_version="4.17", these are not needed anymore
#     pytorch_version="1.10",
#     py_version="py38",
)

predictor = huggingface_model.deploy(
    initial_instance_count=1,
    instance_type="ml.m5.xlarge"
)
```
12. Run this final command in Jupyter Notebook once predictor is done.
```python
predictor.predict({
    "inputs": "The weather is"
})
```
13. See error

**Expected behavior**
I expect to see a generated query from the input using the 20 billion parameters pretrained EleutherAI model. 

**Proposed solution**
I suspect I could fix this issue if I all together ditched the huggingface Sagemaker library. Also, the model hasn't been updated for the last 8 months, so I'm not sure if it is due to that.

**Environment (please complete the following information):**
 - GPUs: none
- Configs: unsure

**Additional context**
I have tried the other versions of GPT-Neo's like 125M and 2.7B and those have worked perfectly. The reason that I need to extend the Docker container for AWS is to not get another error which is apparently an issue with the latest version of transformers (4.17?) on the default docker is not up to date enough.

**Comment by BjornTheProgrammer** [comment]
Should I report this issue on a different repo, maybe a support ticket to AWS? I assumed this was an issue with the model used on transformers, which is under your jurisdiction, but it could be a Hugging Face Issue.

**Comment by StellaAthena** [comment]
@BjornTheProgrammer sorry this slipped through the cracks. This is an issue with the HF library / SageMaker integration, not with our model. I would take it up with HF or AWS.

**Comment by BjornTheProgrammer** [comment]
@StellaAthena Thank you so much! Will do.
