### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'dp_process_group' when finetuning 1-3B param model

### ISSUE THREAD

**Issue by FayZ676** [EleutherAI/gpt-neox#743]
**Describe the bug**
I am getting the same error as [this issue](https://github.com/EleutherAI/gpt-neox/issues/474) when I try finetune a 1-3B param model.

**To Reproduce**
1. Download [Slim Weights](https://the-eye.eu/public/AI/models/GPT-NeoX-20B/slim_weights/)
2. Run `python prepare_data.py -d ./data -t HFTokenizer --vocab-file ./20B_checkpoints/20B_tokenizer.json`
3. Edit the `1-3B.yml` config file as seen in the screenshots below
4. Run `python ./deepy.py train.py -d configs 1-3B.yml`

**Screenshots**
1-3B.yml configuration
![Screen Shot 2022-12-11 at 12 24 44 PM](https://user-images.githubusercontent.com/94952795/206927075-3e416b5a-2488-4d21-a69d-1b868e23ea80.png)
![Screen Shot 2022-12-11 at 12 25 23 PM](https://user-images.githubusercontent.com/94952795/206927040-b3fcbc0d-c892-41b3-8d45-9d822790052f.png)

**Environment (please complete the following information):**
 - GPUs: 4x 3090's

**Comment by StellaAthena** [comment]
You’re trying to fine tune a 1.3B parameter model, but the actual model you downloaded is a 20B parameter model.

**Comment by FayZ676** [comment]
I see, thank you for the clarification. 

My goal is to finetune NeoX 20B, but I was running into memory problems initially so wasn't sure if it was possible for my current system (4x NVIDIA 3090's 96G total VRAM) to finetune. Is there a way to know the requirements? I didn't find any conclusive advise that relates to my case in the issues. Although I certainly could have missed a useful issue.

**Comment by StellaAthena** [comment]
@FayZ676 Finetuning a model's full weights requires approximately 13 bytes of VRAM per parameter. In the case of NeoX 20B, this would be 260 GB of VRAM. With less VRAM you can instead use a methodology called [Low Rank Adaptation](https://arxiv.org/abs/2106.09685). Unfortunately we don't currently support LoRA natively, but you can check out the code associated with the paper [here](https://github.com/microsoft/LoRA).
