### ISSUE TITLE
Getting text gibberish on pretrained model

### ISSUE THREAD

**Issue by githubbar** [EleutherAI/gpt-neox#745]
**Describe the bug**
Generated text looks random:

{"context": "", "text": " now final changementgesun twoi3la90oller\u00a1 de \u00adasenting3a416oerian\u00adasi dekellSetyan abouti\u00ad1ingroreso58\u00ad1a3denoitled most2o5aalumer en6ap3P'a4ollerullanocerta-ZkyeretireThese Dist de resulting systemAplarleg halfibbschlege hideFollowingSer2aN10", "length": 102, "finished": false, "message": null, "duration_seconds": 27.621978521347046}
...

**To Reproduce**
1. Download pretrained GPT-NeoX-20B model

3. Edit text_generation.yml
  # Text gen type: `input-file`, `unconditional` or `interactive`
  "text-gen-type": "unconditional",

  # Params for all
  "maximum_tokens": 102,
  "temperature": 1.0,
  "top_p": 0.0,
  "top_k": 0,
  "recompute": false,

  # `unconditional`: samples
  "num-samples": 10,

4. Edit 20B.yml
  # Tokenizer /  checkpoint settings - you will need to change these to the location you have them saved in
  "vocab-file": "./20B_checkpoints/20B_tokenizer.json",
  "save": "./20B_checkpoints",
  "load": "./20B_checkpoints",

5. Run python ./deepy.py generate.py -d configs 20B.yml text_generation.yml

**Expected behavior**
Text to be continued in English

**Environment (please complete the following information):**
4 A100 GPUs

**Comment by igor0** [comment]
It may be helpful to post the full stdout and stderr output of `python ./deepy.py generate [...]`.

E.g., if the checkpoint didn't load correctly, there would typically be errors.

**Comment by ahmedavid** [comment]
Experiencing same problem. Finally managed to run the model but it generates gibberish.

`{"context": "Arnold Schwartznegger is a famous actor and", "text": "gnut '\n kept generalhrsoller3 vez de7a413\u00bdotherwiseicaoasal5lera\u00ad2O2,LeHigh10aal\u00ad12pjewS776Pke2a3Da316esoioC1stoallt1The4asimetszo forg Har rei3 de\u00ec demB341stlerh98h1,6yenAsheglerAivHo iC3", "length": 102, "finished": false, "message": null, "duration_seconds": 6.522397518157959}`

**Comment by StellaAthena** [comment]
There’s now an updated version of `configs/20B.yml` on `main` that should fix your problem. If it doesn’t, feel free to re-open this issue and post a copy of the exact config files that you’re using.

**Comment by githubbar** [comment]
With the new 20B.yml config.
 I'm running:

python ./deepy.py generate.py -d configs 20B.yml text_generation.yml

Get error, log below:

 File "/N/u/oleykin/BigRed200/.local/lib/python3.9/site-packages/lm_eval/tasks/race.py", line 46, in RACE
    assert datasets.__version__ == "1.15.1", "RACE requires datasets==1.15.1!"
    assert datasets.__version__ == "1.15.1", "RACE requires datasets==1.15.1!"AssertionError
:     RACE requires datasets==1.15.1!assert datasets.__version__ == "1.15.1", "RACE requires datasets==1.15.1!"
AssertionError
: RACE requires datasets==1.15.1!
AssertionError: RACE requires datasets==1.15.1!
    assert datasets.__version__ == "1.15.1", "RACE requires datasets==1.15.1!"
AssertionError: RACE requires datasets==1.15.1!
--
[log.txt](https://github.com/EleutherAI/gpt-neox/files/10326096/log.txt)

Note:  I commented out  'data-path' line as I cannot get the dataset generated via: 
'''python prepare_data.py -d ./data -t HFTokenizer --vocab-file ./20B_checkpoints/20B_tokenizer.json''' The files are large and processing takes forever I get disconnected.

**Comment by githubbar** [comment]
Works now, thanks.
