### ISSUE TITLE
Unable to run the model "TypeError: __init__() got an unexpected keyword argument 'save_interval'"

### ISSUE THREAD

**Issue by ahmedavid** [EleutherAI/gpt-neox#748]
**Describe the bug**
Unable to run the model "TypeError: __init__() got an unexpected keyword argument 'save_interval'"

**To Reproduce**

Followed the README. 
1.Cloned repo
2.Downloaded weights 
2.Downloaded docker image leogao2/gpt-neox
3.Run Docker:    docker run --rm -it -e NVIDIA_VISIBLE_DEVICES=0,1 --shm-size=1g --ulimit memlock=-1 --mount type=bind,src=$PWD,dst=/gpt-neox leogao2/gpt-neox
4. python deepy.py generate.py ./configs/20B.yml

GOT:

`/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.13) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
NeoXArgs.from_ymls() ['./configs/20B.yml']
Traceback (most recent call last):
  File "deepy.py", line 28, in <module>
    neox_args = NeoXArgs.consume_deepy_args()
  File "/gpt-neox/megatron/neox_arguments/arguments.py", line 346, in consume_deepy_args
    neox_args = cls.from_ymls(
  File "/gpt-neox/megatron/neox_arguments/arguments.py", line 218, in from_ymls
    return cls(**config)
TypeError: __init__() got an unexpected keyword argument 'save_interval'
`

**Environment (please complete the following information):**
 - GPUs: 2xRTXA6000 24GB
- Configs: Ubuntu 20.04, Docker

**Comment by StellaAthena** [comment]
`save_interval` is an argument related to how frequently you save model checkpoints. It should not be used when running inference.

**Comment by ahmedavid** [comment]
Thank you for answering,

This setting is in configs/20B.yml by default. What should I change to avoid this error? I commented it out but got other errors. Thank you

**Comment by StellaAthena** [comment]
What other errors did you get?

**Comment by ahmedavid** [comment]
`mchorse@60787d9335cc:/gpt-neox$ python deepy.py generate.py configs/20B.yml
NeoXArgs.from_ymls() ['configs/20B.yml']
INFO:root:NeoXArgs.calculate_derived() Total number of GPUs determined to be: 2
Traceback (most recent call last):
  File "deepy.py", line 28, in <module>
    neox_args = NeoXArgs.consume_deepy_args()
  File "/gpt-neox/megatron/neox_arguments/arguments.py", line 346, in consume_deepy_args
    neox_args = cls.from_ymls(
  File "/gpt-neox/megatron/neox_arguments/arguments.py", line 218, in from_ymls
    return cls(**config)
  File "<string>", line 194, in __init__
  File "/gpt-neox/megatron/neox_arguments/arguments.py", line 123, in __post_init__
    self.calculate_derived()
  File "/gpt-neox/megatron/neox_arguments/arguments.py", line 758, in calculate_derived
    "save_iters": save_iters,
UnboundLocalError: local variable 'save_iters' referenced before assignment
`

**Comment by haileyschoelkopf** [comment]
Hi, 

if you change `save_interval` to `checkpoint_factor` in 20B.yml this error will go away! We recently changed the configuration arguments for checkpointing.

We need to patch the config YMLs in the repository as a result of this, thanks for raising it. Will do so soon!

**Comment by StellaAthena** [comment]
Closing now that the corrected configs are merged
