### ISSUE TITLE
Cannot download the weights for both slim and full

### ISSUE THREAD

**Issue by jmlongriver12** [EleutherAI/gpt-neox#772]
**Describe the bug**
Cannot download the weights for both slim and full
**To Reproduce**
1. execute "wget --cut-dirs=5 -nH -r --no-parent --reject "index.html*" https://the-eye.eu/public/AI/models/GPT-NeoX-20B/slim_weights/ -P 20B_checkpoints"
2. no responding

**Expected behavior**
can download the weights

**Environment (please complete the following information):**
 - GPUs:
- Configs:

**Additional context**

**Comment by StellaAthena** [comment]
It works for me. What's the error you're getting?

**Comment by jmlongriver12** [comment]
it works now, thanks
