### ISSUE TITLE
Can't download Slim model weights from the-eye.eu

### ISSUE THREAD

**Issue by ooofest** [EleutherAI/gpt-neox#775]
**Describe the bug**
When attempting to use the "wget" README command for downloading the Slim weights, although a connection to the port is established no files are transferred.

**To Reproduce**
1.  Open a Command Prompt as an Administrator
2. Clone the repo at https://github.com/EleutherAI/gpt-neox.git
3. Change to the gpt-neox directory that was created
4. Use the README command for obtaining Slim weights: **wget --cut-dirs=5 -nH -r --no-parent --reject "index.html*" https://the-eye.eu/public/AI/models/GPT-NeoX-20B/slim_weights/ -P 20B_checkpoints**
5. A connection is made, but no files are downloaded.

**Expected behavior**
In step (5.) the Slim weights-related files should be downloaded from the-eye.eu to the local system.

**Proposed solution**
Perhaps a different URL/server is needed?

**Screenshots**
Output from attempted wget command:

> D:\gpt-neox>wget --cut-dirs=5 -nH -r --no-parent --reject "index.html*" https://the-eye.eu/public/AI/models/GPT-NeoX-20B/slim_weights/ -P 20B_checkpoints
> --15:21:53--  https://the-eye.eu/public/AI/models/GPT-NeoX-20B/slim_weights/
>            => `20B_checkpoints/index.html'
> Resolving the-eye.eu... 162.213.130.6
> Connecting to the-eye.eu[162.213.130.6]:443... failed: No such file or directory.
> Retrying.
> 
> --15:22:14--  https://the-eye.eu/public/AI/models/GPT-NeoX-20B/slim_weights/
>   (try: 2) => `20B_checkpoints/index.html'
> Connecting to the-eye.eu[162.213.130.6]:443... connected.

(No progress is made after that point.)

**Environment (please complete the following information):**
 - GPUs: Asus GTX-3090 (24GB)
- Configs: Windows 10 Pro, 64GB RAM, 1.7TB free drive space

**Comment by haileyschoelkopf** [comment]
Hi! Do you still have this issue if you try again? I also noticed the-eye.eu was down a day ago, but I'm now able to access the site in my browser.

cc @dashstander

**Comment by ooofest** [comment]
> Hi! Do you still have this issue if you try again? I also noticed the-eye.eu was down a day ago, but I'm now able to access the site in my browser.
> 
> cc @dashstander

Thanks for your response - it had been like this for the past couple of days of trying and just attempting it again the-eye.au seems back up, so the pulls are working now.

I'll close the report.

**Comment by haileyschoelkopf** [comment]
Fantastic! glad it's back up.
