### ISSUE TITLE
[WARNING] [engine.py:1519:load_checkpoint] Unable to find latest file at EleutherAI/gpt-neox-20b/latest

### ISSUE THREAD

**Issue by sasaadi** [EleutherAI/gpt-neox#777]
Hi,

I want to evaluate the huggingface checkpoints on tasks in the lm evaluation harness framework using the following command:

`python ./deepy.py evaluate.py ./configs/20B.yml --eval_tasks triviaqa piqa`

and I set the following arguments in the 20B.yml file:

```
  "vocab-file": "./20B_checkpoints/20B_tokenizer.json",
  "load": "EleutherAI/gpt-neox-20b",
```

and left the other arguments as they are.

When I run the code, I receive the following warning 
`[WARNING] [engine.py:1519:load_checkpoint] Unable to find latest file at EleutherAI/gpt-neox-20b/latest, if trying to load latest checkpoint please ensure this file exists or pass an explicit checkpoint tag when loading a checkpoint.`

and the performance on  piqa is:
```
'piqa': {'acc': 0.5402611534276387,
                      'acc_norm': 0.5250272034820457,
                      'acc_norm_stderr': 0.01165120096762371,
                      'acc_stderr': 0.011627942981817168}
```
I was wondering if the correct checkpoints from huggingface are loaded or did I miss any argument in the config file to properly load the model?

Thanks.

**Comment by haileyschoelkopf** [comment]
Hi! 

The GPT-NeoX-20b weights on Huggingface are not compatible with this codebase--the checkpoint has been ported to Huggingface's model implementation and checkpoint loading code.

To use NeoX-20b with `evaluate.py`, you'll need to download the _slim weights._ Instructions can be found at https://github.com/EleutherAI/gpt-neox#gpt-neox-20b !
