### ISSUE TITLE
Run code on slurm

### ISSUE THREAD

**Issue by sasaadi** [EleutherAI/gpt-neox#784]
Hi,

When I run the code on slurm, I set ` deepspeed_slurm=true` and `"distributed-backend": "nccl"` and `"launcher": "slurm"`. Model and pipeline paralellism are set to 1 for now. In my slurm job submission, I set the following parameters:

> #SBATCH --gres=gpu:8         
> #SBATCH --time=00:30:00                   
> #SBATCH --nodes=1
> #SBATCH --cpus-per-task=8
> #SBATCH --ntasks-per-node=8
> 
> export MASTER_PORT=$ I set this parameter
> export WORLD_SIZE=$  I set this parameter
> export MASTER_ADDR=$  I set this parameter
> 
> srun python ./deepy.py evaluate.py ./configs/20B.yml --eval_tasks piqa

When I run the job, I always get the following error after partitioning the layers:

> File "evaluate.py", line 76, in <module>
>     main()
>   File "evaluate.py", line 35, in main
>     model, neox_args = setup_for_inference_or_eval(use_cache=False)
>   File "..../gpt-neox/megatron/utils.py", line 437, in setup_for_inference_or_eval
>     initialize_megatron(neox_args)
>   File "..../gpt-neox/megatron/initialize.py", line 75, in initialize_megatron
>     finish_mpu_init()
>   File ...../gpt-neox/megatron/initialize.py", line 51, in finish_mpu_init
>     _initialize_distributed(neox_args=neox_args)
>   File "...../gpt-neox/megatron/initialize.py", line 151, in _initialize_distributed
>     distributed.init_distributed(
>   File ...../python3.8/site-packages/deepspeed/utils/distributed.py", line 49, in init_distributed
>     torch.distributed.init_process_group(backend=dist_backend,
>   File "...../python3.8/site-packages/torch/distributed/distributed_c10d.py", line 500, in init_process_group
>     store, rank, world_size = next(rendezvous_iterator)
>   File "......../python3.8/site-packages/torch/distributed/rendezvous.py", line 190, in _env_rendezvous_handler
>     store = TCPStore(master_addr, master_port, world_size, start_daemon, timeout)
> RuntimeError: Address already in use

Here is where the proccess is killed:

>  [INFO] [module.py:363:_partition_layers] Partitioning pipeline stages with method type:transformer|mlp
> stage=0 layers=49
>      0: EmbeddingPipe
>      1: _pre_transformer_block
>      2: ParallelTransformerLayerPipe
> ....
>     45: ParallelTransformerLayerPipe
>     46: _post_transformer_block
>     47: NormPipe
>     48: ParallelLinearPipe
>   loss: partial
> Killing subprocess 116255
> Killing subprocess 116260

The same error happens if I set pip-parallel-size to 2. 

So, it seems that the gpus get busy with the first processes and they don't become free for the next process.

I am wondering if I have missed setting any parameters in the config file or in the slurm job submission?

Thanks.

-- 
Here is my full config file:

{
  "vocab-file": "./20B_checkpoints/20B_tokenizer.json",
  "load": "./20B_checkpoints",
  "checkpoint_validation_with_forward_pass": false,
  "pipe-parallel-size": 1,
  "model-parallel-size": 1,
  "num-layers": 44,
  "hidden-size": 6144,
  "num-attention-heads": 64,
  "seq-length": 2048,
  "max-position-embeddings": 2048,
  "norm": "layernorm",
  "pos-emb": "rotary",
  "rotary_pct": 0.25,
  "no-weight-tying": true,
  "gpt_j_residual": true,
  "output_layer_parallelism": "column",
  "scaled-upper-triang-masked-softmax-fusion": true,
  "bias-gelu-fusion": true,
  "optimizer": {
    "type": "Adam",
    "params": {
      "lr": 0.97e-4,
      "betas": [0.9, 0.95],
      "eps": 1.0e-8,
      "comm_backend_name": "nccl"
      }
      },
  "min_lr": 0.97e-5,
  "zero_optimization": {
  "stage": 1,
  "allgather_partitions": true,
  "allgather_bucket_size": 1260000000,
  "overlap_comm": true,
  "reduce_scatter": true,
  "reduce_bucket_size": 1260000000,
  "contiguous_gradients": true,
  },
  "train_micro_batch_size_per_gpu": 4,
  "gradient_accumulation_steps": 32,
  "data-impl": "mmap",
  "split": "995,4,1",
  "checkpoint-activations": true,
  "checkpoint-num-layers": 1,
  "partition-activations": true,
  "synchronize-each-layer": true,
  "gradient_clipping": 1.0,
  "weight-decay": 0.01,
  "hidden-dropout": 0,
  "attention-dropout": 0,
  "fp16": {
    "fp16": true,
    "enabled": true,
    "loss_scale": 0,
    "loss_scale_window": 1000,
    "initial_scale_power": 12,
    "hysteresis": 2,
    "min_loss_scale": 1
    },
  "train-iters": 150000,
  "lr-decay-iters": 150000,
  "distributed-backend": "nccl",
  "lr-decay-style": "cosine",
  "warmup": 0.01,
  "checkpoint-factor": 500,
  "eval-interval": 1000,
  "eval-iters": 10,
  "log-interval": 1,  #2
  "steps_per_print": 1, #2
  "wall_clock_breakdown": false,
  "tokenizer_type": "HFTokenizer",
  "tensorboard-dir": "./tensorboard",
  "log-dir": "./logs",
  "use_wandb": false,
  "launcher": "slurm",
  "deepspeed_slurm": true,
}

**Comment by Quentin-Anthony** [comment]
This will be fixed by https://github.com/EleutherAI/gpt-neox/pull/859
