### ISSUE TITLE
DeeperSpeed `eb7f5cff` version branch cannot be found

### ISSUE THREAD

**Issue by nomadlx** [EleutherAI/gpt-neox#785]
I followed the tutorial to install the `requirements/requirements.txt`, but DeeperSpeed `eb7f5cff` version branch cannot be found, can you provide a correct DeeperSpeed branch version information?

**Comment by StellaAthena** [comment]
It is in fact [right here](https://github.com/EleutherAI/DeeperSpeed/tree/eb7f5cff) so I'm not sure why you'd be having problems with it. Try unpinning the commit and seeing what happens.

**Comment by nomadlx** [comment]
Thank you very much. This is my mistake. But unfortunately, it raise an out of memory error during I try to finetune 20B model in my machine 8 x A40 (44G). I follow the configure `configs/20B.yml` in repo, only different is `train_micro_batch_size_per_gpu=1`.  
I'm not sure if this machine can run it? If so, what parameters should I adjust to reduce its GPU memory usage? And why is it that when I set zero_optimization to level 2 or 3, it lacks more memory(when it crashes) than when level 1?

**Comment by zscwind** [comment]
> It is in fact [right here](https://github.com/EleutherAI/DeeperSpeed/tree/eb7f5cff) so I'm not sure why you'd be having problems with it. Try unpinning the commit and seeing what happens.

I am trying install deepspeed with the command: sh install.sh in the branch **eb7f5cff** as you gived, but errors ocurrs as following:
`    from ..op_builder import CPUAdmBuilder`
`ModuleNotFoundError: No module named 'deepspeed.ops.op_builder'`

**Comment by StellaAthena** [comment]
I am closing this issue as the original problem is solved and the new problem is duplicative of #797. Please continue this conversation there.
