### ISSUE TITLE
Make `prepare_data.py` more robust

### ISSUE THREAD

**Issue by Quentin-Anthony** [EleutherAI/gpt-neox#788]
`prepare_data.py` is entirely silent in case of issues. Examples include: 
- if data directory exists or files already exist (e.g. `<data_dir>/enron/enron_emails.jsonl.zst`) but are empty/corrupted, `prepare_data.py` will silently exit. We should at least support a flag to force redownloads, and simple checks for corrupt or empty files would be nice to have
- If downloads fail (e.g. https://github.com/EleutherAI/gpt-neox/blob/aae696d7022f66351f2fa8870a7b76a85ee3e8f7/tools/corpora.py#L161 is sometimes unreachable), `prepare_data.py` silently fails and exits. We should either error out or explicitly warn about files that fail to download.

**Comment by StellaAthena** [comment]
Increasing robustness of this command is definitely a good thing. The issue with the Enron email file specifically is that we are relying on a third party host that no longer exists. I recommend either uploading the dataset to HuggingFace or changing it to download a single shard of the Pile from the-eye.eu. Ultimately we don’t really care about models trained on Enron, it was just a convenient small dataset to get people up and running with.

**Comment by Quentin-Anthony** [comment]
My original concerns were addressed in https://github.com/EleutherAI/gpt-neox/pull/820

@StellaAthena -- I agree that enron is a dummy dataset, but I find it useful to test new setups on dummy data before downloading/tokenizing a large dataset like the Pile. Even a single shard of the Pile can take a while, which is why I replaced enron with enwik8 as the standard in https://github.com/EleutherAI/gpt-neox/pull/833. Users can grab a shard of the pile with `prepare_data.py pile_subset`

**Comment by StellaAthena** [comment]
> My original concerns were addressed in https://github.com/EleutherAI/gpt-neox/pull/820
> 
> @StellaAthena -- I agree that enron is a dummy dataset, but I find it useful to test new setups on dummy data before downloading/tokenizing a large dataset like the Pile. Even a single shard of the Pile can take a while, which is why I replaced enron with enwik8 as the standard in https://github.com/EleutherAI/gpt-neox/pull/833. Users can grab a shard of the pile with prepare_data.py pile_subset

I’m content with this resolution!
