### ISSUE TITLE
Where is the source code of chatbot gpt, I want to learn it, thank you all! !

### ISSUE THREAD

**Issue by suiyan538** [EleutherAI/gpt-neox#793]
**Is your feature request related to a problem? Please describe.**
Where is the source code of chatbot gpt, I want to learn it, thank you all! !

**Describe the solution you'd like**
Where is the source code of chatbot gpt, I want to learn it, thank you all! !

**Describe alternatives you've considered**

**Additional context**

**Comment by StellaAthena** [comment]
This is not an appropriate venue for this post.
