### ISSUE TITLE
Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! 

### ISSUE THREAD

**Issue by zscwind** [EleutherAI/gpt-neox#798]
**Describe the bug**
>**1-3B model trained with  8 gpus and 1 node, when i try to convert it to hf model：**
Traceback (most recent call last):
  File "./tools/convert_to_hf.py", line 292, in <module>
    hf_model = convert(args.input_dir, loaded_config, args.output_dir)
  File "./tools/convert_to_hf.py", line 156, in convert
    "weight": torch.cat(
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensors in method wrapper_cat)

**To Reproduce**
>python ./tools/convert_to_hf.py --input_dir checkpoints/global_step30000 --config_file configs/1-3B.yml --output_dir ../huggingface

**Expected behavior**
> The expected result is  I could convert ckpt to huggingface model properly

**Proposed solution**
If you have an idea for how we can fix this problem, describe it here.
> I am not sure if the model  is incorrectly configed, or I need to modify the convert code.

**Screenshots**

**Environment (please complete the following information):**
 >-  CUDA 11.3
 >- torch 1.13.0.dev20220727+cu113
 >- python 3.8.16

**Additional context**
>In training stage,  the`model-parallel-size=8` in yml conf:
   "pipe-parallel-size": 1,
   **"model-parallel-size": 8**

**Comment by StellaAthena** [comment]
Your issue has boilerplate that hasn’t been filled out. Please complete the template.

**Comment by zscwind** [comment]
> Your issue has boilerplate that hasn’t been filled out. Please complete the template.

yeah，I had completed the template. Help ms see what happens, thank you.

**Comment by StellaAthena** [comment]
@haileyschoelkopf it seems like there’s an issue with your HF conversation code?

**Comment by haileyschoelkopf** [comment]
Hi @zscwind ! I haven't encountered the exact error you're reporting, but adding

`map_location=torch.device('cuda:0')` to line 53 as a keyword arg to torch.load should fix this and load all your model weights to device 0. Alternatively, `map_location=torch.device('cpu')` should also have the same effect.

I'll push this fix later today :)

**Comment by zscwind** [comment]
> 

Yeah，I have tried your method. It works, thank you!

**Comment by zscwind** [comment]
> Hi @zscwind ! I haven't encountered the exact error you're reporting, but adding
> 
> `map_location=torch.device('cuda:0')` to line 53 as a keyword arg to torch.load should fix this and load all your model weights to device 0. Alternatively, `map_location=torch.device('cpu')` should also have the same effect.
> 
> I'll push this fix later today :)

Yeah，I have tried your method. It works, thank you!
