### ISSUE TITLE
Modify READMI for preprocess_data.py

### ISSUE THREAD

**Issue by githubbar** [EleutherAI/gpt-neox#804]
Running  preprocess_data.py I kept getting error "No valid file(s) found in myfile.json"
until I stumbled somewhere and renamed the file to "myfile.jsonl".

The list of valid file extensions should be in the README.

**Comment by StellaAthena** [comment]
It is

> To prepare your own dataset for training with custom data, format it as one large [jsonl](https://jsonlines.org/)-formatted file with each item in the list of dictionaries being a separate document. The document text should be grouped under one JSON key, i.e "text". Any auxiliary data stored in other fields will not be used.
