### ISSUE TITLE
Does the model support the task in Chinese?

### ISSUE THREAD

**Issue by wsh2836741** [EleutherAI/gpt-neox#844]
Thanks for your good job，and does the model support the task in Chinese?

**Comment by WaveLi123** [comment]
Does the original 20B_tokenizer.json support Chinese data?

**Comment by StellaAthena** [comment]
No it does not.

**Comment by nomadlx** [comment]
> 不，不是的。

Can you provide training code for 20B_tokenizer? This is a byte-level BPE algorithm, I didn't find the public code, or did I miss something?
