### ISSUE TITLE
RuntimeError: probability tensor contains either inf, nan or element < 0

### ISSUE THREAD

**Issue by believeland23** [EleutherAI/gpt-neox#871]
my environment is
GPU: V100-32G
torch: 1.13.1+cu116
python: 3.7.13

I load the model by using LoRA:
tokenizer = AutoTokenizer.from_pretrained("EleutherAI/gpt-neox-20b")
model = AutoModelForCausalLM.from_pretrained("EleutherAI/gpt-neox-20b", device_map="auto", load_in_8bit=True)

And when run the model.generate the error will occur: RuntimeError: probability tensor contains either inf, nan or element < 0 at "next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)"
![image](https://user-images.githubusercontent.com/67883265/229757222-0075c334-d58c-486a-9d89-ffd26f29327c.png)

I printed the values and found that from "next_token_scores = logits_processor(input_ids, next_token_logits)", all the elements of the tensor is "nan".
![image](https://user-images.githubusercontent.com/67883265/229757550-c79b99e1-4ab4-4c1f-a6c6-93edaa9189f5.png)
![image](https://user-images.githubusercontent.com/67883265/229757579-9d5329c8-2387-4465-8406-3e880c1d3987.png)

**Comment by StellaAthena** [comment]
This is an issue that should be reported to the HF transformers or PEFT library. Unless it’s a problem with the pretrained model weights, HuggingFace will be in a better position to help with issues using our models in their library.
