### ISSUE TITLE
Does it work without Nvidia GPU? 

### ISSUE THREAD

**Issue by Maniues** [EleutherAI/gpt-neox#872]

**Comment by StellaAthena** [comment]
Yes, you can use this branch to run on AMD GPUs: https://github.com/EleutherAI/gpt-neox/tree/AMD

**Comment by StellaAthena** [comment]
If you’re asking if this can be run on AMD GPUs, the answer is yes.

if you’re asking if this can be run on CPU, the answer is no.

If you’re asking if this can be run on TPU, the answer is yes but not nearly as efficiently.

**Comment by StellaAthena** [comment]
This code may or may not run on a CPU. We have no given any consideration to running on non-GPU devices.

It's technically impossible to _do anything useful with it_ on a CPU, because it would take years to train a small language model on a CPU.

**Comment by jackzhp** [comment]
Can this run on a laptop with one GPU? Thanks.

**Comment by StellaAthena** [comment]
> Can this run on a laptop with one GPU? Thanks.

Yes, but you should probably use a much simpler library.
