### ISSUE TITLE
1.0 HF conversion script fails on Python 3.8

### ISSUE THREAD

**Issue by syskn** [EleutherAI/gpt-neox#875]
**Describe the bug**

While the official recommended Python version for NeoX is 3.8, **convert_v1.0_to_hf.py** only works with Python 3.9 or later due to minor incompatibility (tested on Python 3.8.10).

>TypeError: 'type' object is not subscriptable

**Suggested change**

Modify `list[torch.Tensor]` at the line 42 to `List[torch.Tensor]` (capitalized L)
Add import `from typing import List`

**Comment by cateto** [comment]
same here.

will it merge to main branch?

**Comment by haileyschoelkopf** [comment]
Hi, this should be fixed in #877 --can you share what commit you experience this error in?

**Comment by cateto** [comment]
@haileyschoelkopf sure!
https://github.com/EleutherAI/gpt-neox/commit/37195333b6805da4a4ecb341bae1da308045e60a

**Comment by StellaAthena** [comment]
@cateto Try checking out the `fix-convert-py3.8` branch and see if that works.

**Comment by haileyschoelkopf** [comment]
It looks like this got reverted in https://github.com/EleutherAI/gpt-neox/commit/29b968de2b522ad4919f33d671e3e79d4658948c by merge conflicts accidentally, I’ll re-fix this as soon as I’m back to a computer!

**Comment by cateto** [comment]
thank you 😸

**Comment by haileyschoelkopf** [comment]
This is fixed in #931 !
