### ISSUE TITLE
Some problems when using generate.py and how to fix it

### ISSUE THREAD

**Issue by DaoD** [EleutherAI/gpt-neox#883]
1. The first problem has been reported in this [issue](https://github.com/EleutherAI/gpt-neox/issues/854).
    - To tackle the first problem, I simply comment out the line at https://github.com/EleutherAI/gpt-neox/blob/main/megatron/text_generation_utils.py#L448
2. Then, the program will be crashed at the line https://github.com/EleutherAI/gpt-neox/blob/main/megatron/model/transformer.py#L443
3. After clearly comparing with the original Megatron LM (https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/model/transformer.py#L382) and Flash Attention (https://github.com/HazyResearch/flash-attention/blob/main/flash_attn/flash_attn_interface.py#L280). I think the current version of the flash attention in GPT-NeoX can only support **training**, but not **inference**. This is because:
    - The QKV packed attention function can only be used in training as the length of Q == K == V.
    - In inference, the length of Q is always one (the current decoding step), but the lengths of K and V are increasing (equal to the number of the previous decoded steps).
4. I fixed this problem by also introducing KV packed attention function as https://github.com/HazyResearch/flash-attention/blob/main/flash_attn/flash_attn_interface.py#L280. Then, during inference, using this function rather than the QKV packed version. 
5. Currrently, I can run the generation process successfully. However, I'm not sure if it is the perfect way to tackle this problem. 
6. Feel free to have a discussion here.

**Comment by DaoD** [comment]
This issue can be tackled by the commit. 
https://github.com/EleutherAI/gpt-neox/pull/862

**Comment by Quentin-Anthony** [comment]
Fixed by https://github.com/EleutherAI/gpt-neox/pull/862
