### ISSUE TITLE
cant preprocess_data using custom tokinzer.

### ISSUE THREAD

**Issue by snirbenyosef** [EleutherAI/gpt-neox#898]
**Describe the bug**
from the docs i'm trying to use Custom Data and prepare it.
i have created a jsonl-formatted file, and I'm trying to use

and i see this line:
"(alternatively, you can provide any tokenizer file that can be loaded by Hugging Face's tokenizers library with the Tokenizer.from_pretrained() command)"

so i changed the preprocess_data.py file to use:
`AutoTokenizer.from_pretrained("stabilityai/stablelm-tuned-alpha-7b")`
i have changed it in the encoder and in the main function.
but i keep getting this error:
`0it [00:00, ?it/s]Traceback (most recent call last):
  File "tools/preprocess_data.py", line 248, in <module>
    main()
  File "tools/preprocess_data.py", line 218, in main
    for i, (doc, bytes_processed) in enumerate(encoded_docs, start=1):
  File "tools/preprocess_data.py", line 194, in <genexpr>
    encoded_docs = (encoder.encode(doc) for doc in fin)
  File "tools/preprocess_data.py", line 62, in encode
    doc_ids[-1].append(Encoder.tokenizer.eod)
AttributeError: 'GPTNeoXTokenizerFast' object has no attribute 'eod'`

**To Reproduce**
just run the following code:
`python3 tools/preprocess_data.py --input /dir/new-test/output.jsonl --output-prefix /data/mydataset --dataset-impl mmap  --tokenizer-type GPT2BPETokenizer --append-eod`

**Expected behavior**
the preprocess data files should be created.

**Environment (please complete the following information):**
 - GPUs: 1 A100 100GB
- Configs:

**Comment by StellaAthena** [comment]
I’m sorry you’re having this issue. It seems like error has nothing to do with our library, unfortunately. You’re trying to add an end-of-document token to the tokenizer and the HF tokenizer library doesn’t think it supports it. If this is in error, you should report it to HF’s tokenizers library which is being used under the hood here.
