### ISSUE TITLE
Add arguments for turning off fused kernels to work with native pytorch

### ISSUE THREAD

**Issue by mayank31398** [EleutherAI/gpt-neox#906]
This is needed for running on non-nvidia architectures.

**Comment by mayank31398** [comment]
I plan to work on this :)

**Comment by Quentin-Anthony** [comment]
I believe we already support this with:

```
  "scaled-upper-triang-masked-softmax-fusion": false,
  "bias-gelu-fusion": false,
```

e.g. https://github.com/EleutherAI/gpt-neox/blob/main/configs/20B.yml#L31-L32
