### ISSUE TITLE
Do pythia untied embedding and unembedding matrics?

### ISSUE THREAD

**Issue by Life-0-1** [EleutherAI/gpt-neox#913]
In the *Pythia* paper, it is stated that embedding and unembedding matrics are untied. 

But I find that config files of all kinds of pythia models are with the `no_weight_tying` remaining a default value of `False`, which results a tying between embed and unembed layers. 

Is this a bug? What setting did you actually use while training pythia?

**Comment by haileyschoelkopf** [comment]
Which config files are you looking at? the ones in the Pythia repo and the ones here https://github.com/EleutherAI/gpt-neox/blob/main/configs/pythia/1-4B.yml use the value “no-weight-tying”: true as expected.

**Comment by Life-0-1** [comment]
> Which config files are you looking at? the ones in the Pythia repo and the ones here https://github.com/EleutherAI/gpt-neox/blob/main/configs/pythia/1-4B.yml use the value “no-weight-tying”: true as expected. 

Sorry, I Made a mistake. I searched config files and found no `no_weight_tying`() , but there is `no-weight-tying`. 

"-" and "_" are different from readme and config files.

**Comment by StellaAthena** [comment]
@Life-0-1 what readme are you talking about? The one in `gpt-neox/configs` uses `-`

**Comment by Life-0-1** [comment]
> @Life-0-1 what readme are you talking about? The one in `gpt-neox/configs` uses `-`

`gpt-neox/configs/neox_arguments.md` this one.

**Comment by StellaAthena** [comment]
Opened an issue to fix the inconsistency https://github.com/EleutherAI/gpt-neox/issues/920
