### ISSUE TITLE
[question] How were the default values of `checkpoint-factor` selected?

### ISSUE THREAD

**Issue by obicons** [EleutherAI/gpt-neox#914]
Apologies if this question is better posed in a different forum. 

My question is how were the example values of `checkpoint-factor` selected? For example, [this value](https://github.com/EleutherAI/gpt-neox/blob/586f5149ea948cc46b270ddb9e8076628868c34a/configs/2-7B.yml#L82). I'm interested because I'm working on a similar problem, and wanted to know if there are any best practices I should be aware of.

I appreciate any information folks can share.

**Comment by StellaAthena** [comment]
Completely arbitrarily. `checkpoint-factor` is one of the configs that users should change depending on their dataset and needs.

**Comment by obicons** [comment]
Thank you, @StellaAthena!
