### ISSUE TITLE
Why GPT2Dataset shuffles documents?

### ISSUE THREAD

**Issue by kosstbarz** [EleutherAI/gpt-neox#923]
I've noticed that GPT2Dataset shuffles not only samples, but documents.
`self.doc_idx, self.sample_idx, self.shuffle_idx = _build_index_mappings(`
I assume shuffling of samples can be easily done without indexes. It would simplify logic a lot.
So my question is - what is the reason to shuffle documents? Looks like I'm missing something important.

**Comment by StellaAthena** [comment]
Training on un-shuffled or poorly shuffled data is a very easy way to have your model’s loss explode. We take care to shuffle throughly because some users will have data that is well sorted on disk.
