### ISSUE TITLE
Import megatron.data.helpers failing

### ISSUE THREAD

**Issue by convexstrictly** [EleutherAI/gpt-neox#934]
Following the documented steps for training in the README resulted in import errors in Python 3.9.16 when trying to train a model.  Similar problems were reported a while ago in the megatron mailing list when python3-config was not present.  However that is not the situation in my case.

    Traceback (most recent call last):
      File "/src/gpt-neox/train.py", line 27, in <module>
        pretrain(neox_args=neox_args)
      File "/src/gpt-neox/megatron/training.py", line 203, in pretrain
        ) = build_train_valid_test_data_iterators(neox_args=neox_args)
      File "/src/gpt-neox/megatron/data/data_utils.py", line 400, in build_train_valid_test_data_iterators
        train_ds, valid_ds, test_ds = build_train_valid_test_datasets(
      File "/src/gpt-neox/megatron/data/data_utils.py", line 139, in build_train_valid_test_datasets
        train_dataset = build_dataset(0, "train")
      File "/src/gpt-neox/megatron/data/data_utils.py", line 127, in build_dataset
        dataset = GPT2Dataset(
      File "/src/gpt-neox/megatron/data/gpt2_dataset.py", line 52, in __init__
        self.doc_idx, self.sample_idx, self.shuffle_idx = _build_index_mappings(
      File "/src/gpt-neox/megatron/data/gpt2_dataset.py", line 173, in _build_index_mappings
        from megatron.data import helpers
    ImportError: cannot import name 'helpers' from 'megatron.data' (/src/gpt-neox/megatron/data/__init__.py)

**To Reproduce**
1. pip install -r requirements/requirements.txt
1. python ./megatron/fused_kernels/setup.py install                                                                                                   
1. python prepare_data.py -d ./data
1. python ./deepy.py train.py -d configs 19M.yml local_setup.yml

**Environment**
Python 3.9.16
GPU: RTX A5000
CUDA 11.6
torch 2.0.1+cu117

There's a discrepancy between torch CUDA version and the installed CUDA.  Don't know whether that could be relevant.

**Comment by Quentin-Anthony** [comment]
Looks like the C++ dataset `helpers.so` failed to build. Can you head to `gpt-neox/megatron/data`, run `make`, and post the error message here?

**Comment by convexstrictly** [comment]
Thanks to @Quentin-Anthony who found the underlying cause. He pointed out to me (outside this ticket) that the library `helpers.cpython-38-x86_64-linux-gnu.so`  references Python 3.8 whereas I was using Python 3.9.  With that information I was able to track down the underlying cause. The `python3-config` in the provider's standard Cloud GPU VM was misconfigured:

    $ ls -al $(which python3)
    lrwxrwxrwx 1 root root 18 Jan 25 15:26 /usr/local/bin/python3 -> /usr/bin/python3.9
    $ ls -al $(which python3-config)
    lrwxrwxrwx 1 root root 16 Mar 13 2020 /usr/bin/python3-config -> python3.8-config

I have filed a ticket with the provider.

So the underlying cause is similar to other cases online of megatron.data.helpers not being built because of problems with`python3-config`.

The following temporary workaround solved the problem: Changing `python3-config` in 
`gpt-neox/megatron/data/Makefile` to `python3.9-config` to match the `python3.9` executable I am using.

**Comment by StellaAthena** [comment]
@convexstrictly I'm not very familiar with Cython, but is this something where we can make modifications to make the code more flexible? If your temporary work-around is general, would it make sense to add a warning to the `readme`?

**Comment by convexstrictly** [comment]
@StellaAthena What happened here is that the `megatron.data` Makefile uses `python-3.config` to construct the name of the dynamically linked library: `helpers.cpython-38-x86_64-linux-gnu.so` for Python 3.8, or `helpers.cpython-38-x86_64-linux-gnu.so` for Python 3.9.  Since the provider's VM had a `python3-config` that was misconfigured, a `helper.*.so` with the wrong version was being generated, and because Python could not find the shared library, it complained that `helpers` did not exist.

My workaround is not general.  I hard-coded it to use `python3.9-config`.  I could modify the Makefile to call a shell-script that attempts to find the right `python3-config`.  But there are two problems:
- I am uncertain how robust my shell script would be; given the variety of ways in which Python is set up.
- even assuming the script works correctly, I wonder how many cases of misconfiguration my script would actually cover given the variety of ways environments can be misconfigured.

I suggest two possible courses of action (not mutually exclusive) :

- Create a **Troubleshooting** section, and document what to look for if they encounter this error.
- Create a shell or Python script that checks for problems in their environment.  It does not try to work around the errors, merely finds them, reports on them, and suggests workarounds.

I think the second course of action is particularly attractive if you get questions about failures that tend to be problems with users' environments, the same questions get asked repeatedly, and you decide not to workaround these issues in the code base.  I am happy to document workarounds for this error in the **Troubleshooting** section, or help with writing a shell/Python script to detect commonly-occurring problems with users' environments.
