### ISSUE TITLE
How to preprocess data from plaintext

### ISSUE THREAD

**Issue by Maniues** [EleutherAI/gpt-neox#935]
I want to test gpt-neox to make a tiny GPT model.
I would like to train it on some plaintext files.
I converted it into JSONL file and... I stuck in Tokenization.
I don't know how to do that. I have only plaintext and I want to make a vocab and merge files from it to put them into preprocess_data. I use non-English data, so I want to make these files myself without downloading existing English vocab/merge.

I used the same plaintext files to make a small GPT model using nanoGPT, but I want to do the same in NeoX, because nanoGPT does not support any other format, and because I want to fine-tune some other models in the future (+ test GPT-NeoX library).

**Comment by StellaAthena** [comment]
Apologies for the confusion caused by the read me. Could you submit a PR with some corrections?
