### ISSUE TITLE
parameters

### ISSUE THREAD

**Issue by 1660678083Alice** [EleutherAI/gpt-neox#94]
How to display total parameters?
How to adjust parameters？I changed some numbers in gpt3_small.json, but it didn't work

**Comment by StellaAthena** [comment]
To change the model parameters you want to create a new config file modeled after `gpt3small`. The values to modify are
```
  "hidden_dim": 768,
  "n_layers": 12,
  "n_heads": 12,
  "dim_head": 64,
```
