### ISSUE TITLE
change max-position-embeddings after pretrain.

### ISSUE THREAD

**Issue by guozhiyao** [EleutherAI/gpt-neox#942]
I have pretrain a 13B model with `"pos-emb": "rotary"` and `"seq-length": 2048`. I want to fine tune the model with larger `seq-length`, such as `4096`. Can this fine tune improve the model performance or affect the position embedding?

**Comment by StellaAthena** [comment]
This is an active area of research at EleutherAI. Stop by our discord server and check out [this channel](https://discord.com/channels/729741769192767510/1102979018199932979) to catch up.
