### ISSUE TITLE
[Question] about clearly params

### ISSUE THREAD

**Issue by phamkhactu** [EleutherAI/gpt-neox#945]
I've followed your command to run training model
```
python ./deepy.py train.py -d configs 125M.yml local_setup.yml
```

However, I want to pass clearly params with command. I've tried:
```
$ python deepy.py --user_script train.py --conf_file configs/125M.yml configs/local_setup.yml
```
I get error:
```
/gpt-neox$ python deepy.py --user_script train.py --conf_file configs/125M.yml configs/local_setup.yml
usage: deepy.py [-h] [--conf_dir CONF_DIR] [--wandb_group WANDB_GROUP] [--wandb_team WANDB_TEAM] [--eval_tasks EVAL_TASKS [EVAL_TASKS ...]] [--iteration ITERATION] [--eval_results_prefix EVAL_RESULTS_PREFIX]
                [-H HOSTFILE] [-i SAMPLE_INPUT_FILE] [-o SAMPLE_OUTPUT_FILE] [--autotuning {tune,run}]
                user_script conf_file [conf_file ...]
deepy.py: error: unrecognized arguments: --user_script --conf_file

```
I'm very happy if you can give me clearly command.
Thank you very much!

**Comment by StellaAthena** [comment]
What are “clearly params”?

**Comment by phamkhactu** [comment]
> What are “clearly params”?

Hi @StellaAthena,

The fact, I want to finetune your model, but with my data, I get error --> So I want to debug. If  I want to debug with VSCode, I must give debug clearly arguments for run deep.py file.
For example:
```
"args": ["--user_script","train.py "]
```
[Ref link stackoverflow
](https://stackoverflow.com/questions/51244223/visual-studio-code-how-debug-python-script-with-arguments)

But I can not find detail about this. I run ```deep.py --help``` --> It show helping arguments --> I add arguments --> error above I describe.

**Comment by haileyschoelkopf** [comment]
Based on the stackoverflow post you link, can you just do 

```
"args": ["train.py", "--conf_dir", "configs", "125M.yml", "local_setup.yml"]
```
to pass the args through the VSCode debugger in the format we expect?

**Comment by phamkhactu** [comment]
> Based on the stackoverflow post you link, can you just do
> 
> ```
> "args": ["train.py", "--conf_dir", "configs", "125M.yml", "local_setup.yml"]
> ```
> 
> to pass the args through the VSCode debugger in the format we expect?

Thank you very much, It works
