### ISSUE TITLE
Preconfigured Datasets are not available

### ISSUE THREAD

**Issue by vogt31337** [EleutherAI/gpt-neox#949]
**Describe the bug**
The step:
"Several preconfigured datasets are available, including most components from [the Pile](https://arxiv.org/abs/2101.00027), as well as the Pile train set itself, for straightforward tokenization using the prepare_data.py entry point.

E.G, to download and tokenize the enwik8 dataset with the GPT2 Tokenizer, saving them to ./data you can run:
```
python prepare_data.py -d ./data
```
"
creates an Download error. https://data.deepai.org/enwik8.zip is down / not available

**To Reproduce**
1. Fresh install / git clone
2. `python prepare_data.py -d ./data`

**Expected behavior**
Getting a dataset.

**Proposed solution**
Maybe provide another source or another description how to find such a dataset.

**Screenshots**

**Environment (please complete the following information):**
 - GPUs: 1
- Configs: 20B.yml

**Additional context**

**Comment by vogt31337** [comment]
wget delivers a certificate issue for data.deepai.org. The certificate has expired.

**Comment by StellaAthena** [comment]
Clicking the link that you say is down downloads it for me. Perhaps they had a short outage?
