### ISSUE TITLE
How to change parameters

### ISSUE THREAD

**Issue by Carolingliang** [EleutherAI/gpt-neox#95]
GPT-NeoX is designed to be able to train models in the hundreds of billions of parameters, so how to adjust gpt3_small.json by realizing this

**Comment by joshlk** [comment]
It's still in development 😃

**Comment by StellaAthena** [comment]
> GPT-NeoX is designed to be able to train models in the hundreds of billions of parameters, so how to adjust gpt3_small.json by realizing this

How to choose the optimal parameters for your hardware depends on your specific capabilities. If you can provide information about the hardware you have access to I can provide specific recommendations about parameters. You can also find good information about parameter settings on the DeepSpeed website, https://www.deepspeed.ai/
