### ISSUE TITLE
Support Megatron LayerNorm kernel

### ISSUE THREAD

**Issue by Quentin-Anthony** [EleutherAI/gpt-neox#952]
Upstream Megatron-LM supports a layernorm kernel (https://github.com/microsoft/Megatron-DeepSpeed/tree/main/megatron/fused_kernels) that we should support and evaluate.

- [ ] Port LayerNorm kernel to gpt-neox
- [ ] Test the new LayerNorm kernel and take before/after numbers

**Comment by kamathis4** [comment]
Hey @Quentin-Anthony, is it [this](https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/model/fused_layer_norm.py) you're talking about?

**Comment by StellaAthena** [comment]
> Hey @Quentin-Anthony, is it [this](https://github.com/NVIDIA/Megatron-LM/blob/main/megatron/model/fused_layer_norm.py) you're talking about?

Yes

**Comment by IshanMi** [comment]
I would love to take a stab at this!
