### ISSUE TITLE
How to run gpt-neox with two gtx 1080's?

### ISSUE THREAD

**Issue by therealjr** [EleutherAI/gpt-neox#964]
I have followed the instructions exactly but I appear to run into an out of memory error every time. It doesn't matter what I do to the config file. Can anyone explain to me how to run the batch size as 1? Would that work?

Thanks

**Comment by StellaAthena** [comment]
You should not use this library. This library is specifically designed for training very large models, far larger than what will fit on your GPUs. Given your computing resources, using another library like Hugging Face’s transformers or Meta’s MetaSeq is probably more appropriate.
