### ISSUE TITLE
Any plans on supporting modeling_tf_gpt_neox to hugging face transformers models

### ISSUE THREAD

**Issue by praneethgb** [EleutherAI/gpt-neox#970]
**Is your feature request related to a problem? Please describe.**
To support both tf and pytorch in  hugging face modeling_gpt_neox

**Describe the solution you'd like**
supporting modeling_tf_gpt_neox to hugging face transformers models
https://github.com/huggingface/transformers/blob/main/src/transformers/convert_pytorch_checkpoint_to_tf2.py

**Describe alternatives you've considered**
Custom Tf modules

**Additional context**
https://github.com/huggingface/transformers/tree/main/src/transformers/models/gpt_neox
https://github.com/huggingface/transformers/tree/main/src/transformers/models/gpt2

**Comment by Quentin-Anthony** [comment]
There are no plans to incorporate TF unless either **(a)** the framework becomes less painful to work with, or **(b)** we have a specific research need.
