### ISSUE TITLE
WARNING: shuffle index length is not equal to sample index length

### ISSUE THREAD

**Issue by 1ittlesnow** [EleutherAI/gpt-neox#972]
**Describe the bug**
WARNING: shuffle index length is not equal to sample index length
In Megatron/data/gpt2_dataset.py,  there is a warning in line 67-70. Howvere, the warning always happen. The reason is that shuffle_idx_len always equals sample_idx_len-1 rather than sample_idx_len.

**Comment by StellaAthena** [comment]
Please don’t  close this issue until the corresponding PR has been merged :)
