### ISSUE TITLE
A question about flops calculation

### ISSUE THREAD

**Issue by CSlearnerZM** [EleutherAI/gpt-neox#981]
I try to understand the following function `get_flops` to calculate flops, but I still can't figure out why the parameter `attn` needs to multiply a constant value 60. 

The paper [Efficient Large-Scale Language Model Training on GPU Clusters Using Megatron-LM](https://arxiv.org/pdf/2104.04473.pdf) provides a formula for calculating flops similar to `get_flops`(Page 12). When we don't use the activation-checkpointing, I think `attn` needs to multiply 12 not 60 according to the formula. Of course, it is also possible that I misunderstood.

![截屏2023-06-25 11 19 39](https://github.com/EleutherAI/gpt-neox/assets/135961799/6e6dd054-d13f-4884-b029-962e05c34ac2)

Could you help me to solve the above problem? Thanks!!!

**Comment by dashstander** [comment]
I think you're right! Thanks for bringing this to our attention @CSlearnerZM

**Comment by dashstander** [comment]
Ok, I have a branch that pretty much ports over the Megatron-DeepSpeed calculation from [here](https://github.com/microsoft/Megatron-DeepSpeed/blob/cc3a94c636789f74be2bc6cfc62a3d723fd5d749/megatron/utils.py#L253)
