### ISSUE TITLE
NCCL backend in DeepSpeed not yet implemented

### ISSUE THREAD

**Issue by jiezhangGt** [EleutherAI/gpt-neox#990]
Warning in training log：

[WARNING] [comm.py:152:init_deepspeed_backend] NCCL backend in DeepSpeed not yet implemented
 [INFO] [comm.py:594:init_distributed] cdb=None

is this normal?

**Comment by Quentin-Anthony** [comment]
Yes. It's a generic warning in DeepSpeed that my pure NCCL comms backend (i.e. without going through torch distributed) hasn't been merged in yet.

Safe to ignore.
