### ISSUE TITLE
BF16 Trainning's bug

### ISSUE THREAD

**Issue by jiezhangGt** [EleutherAI/gpt-neox#991]
my config：

`  "fp16": {
    "fp16": false,
    "enabled": false,
    "loss_scale": 0,
    "loss_scale_window": 1000,
    "initial_scale_power": 12,
    "hysteresis": 2,
    "min_loss_scale": 1
    },

  "precision": "bfloat16",
  "bf16": {
      "enabled": true
  },
  "data_types": {"grad_accum_dtype":"fp32"}`

but when saving the model to local, An error has occurred：
`AttributeError: 'BF16_Optimizer' object has no attribute 'fp16_groups'`

**Comment by Desein-Yang** [comment]
It is a bug in deepspeed.
